<h1>목차<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#부산" data-toc-modified-id="부산-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>부산</a></span><ul class="toc-item"><li><span><a href="#동구" data-toc-modified-id="동구-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>동구</a></span></li><li><span><a href="#동래구" data-toc-modified-id="동래구-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>동래구</a></span></li><li><span><a href="#북구" data-toc-modified-id="북구-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>북구</a></span></li><li><span><a href="#강서구" data-toc-modified-id="강서구-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>강서구</a></span></li><li><span><a href="#진구" data-toc-modified-id="진구-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>진구</a></span></li><li><span><a href="#중구" data-toc-modified-id="중구-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>중구</a></span></li><li><span><a href="#기장군" data-toc-modified-id="기장군-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>기장군</a></span></li><li><span><a href="#남구" data-toc-modified-id="남구-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>남구</a></span></li><li><span><a href="#서구" data-toc-modified-id="서구-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>서구</a></span></li><li><span><a href="#사하구" data-toc-modified-id="사하구-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>사하구</a></span></li><li><span><a href="#수영구" data-toc-modified-id="수영구-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>수영구</a></span></li><li><span><a href="#연재구" data-toc-modified-id="연재구-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>연재구</a></span></li></ul></li><li><span><a href="#서울" data-toc-modified-id="서울-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>서울</a></span><ul class="toc-item"><li><span><a href="#광진구" data-toc-modified-id="광진구-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>광진구</a></span></li><li><span><a href="#서대문구" data-toc-modified-id="서대문구-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>서대문구</a></span></li><li><span><a href="#용산" data-toc-modified-id="용산-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>용산</a></span></li><li><span><a href="#도봉구" data-toc-modified-id="도봉구-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>도봉구</a></span></li><li><span><a href="#동대문" data-toc-modified-id="동대문-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>동대문</a></span></li><li><span><a href="#동작구" data-toc-modified-id="동작구-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>동작구</a></span></li><li><span><a href="#관악구" data-toc-modified-id="관악구-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>관악구</a></span></li><li><span><a href="#광진구" data-toc-modified-id="광진구-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span>광진구</a></span></li><li><span><a href="#중랑구" data-toc-modified-id="중랑구-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span>중랑구</a></span></li><li><span><a href="#송파구" data-toc-modified-id="송파구-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>송파구</a></span></li><li><span><a href="#양천구" data-toc-modified-id="양천구-2.11"><span class="toc-item-num">2.11&nbsp;&nbsp;</span>양천구</a></span></li><li><span><a href="#영등포구" data-toc-modified-id="영등포구-2.12"><span class="toc-item-num">2.12&nbsp;&nbsp;</span>영등포구</a></span></li></ul></li><li><span><a href="#인천" data-toc-modified-id="인천-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>인천</a></span><ul class="toc-item"><li><span><a href="#중구" data-toc-modified-id="중구-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>중구</a></span></li><li><span><a href="#미추홀구" data-toc-modified-id="미추홀구-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>미추홀구</a></span></li><li><span><a href="#남동구" data-toc-modified-id="남동구-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>남동구</a></span></li><li><span><a href="#옹진군" data-toc-modified-id="옹진군-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>옹진군</a></span></li><li><span><a href="#서구---보류" data-toc-modified-id="서구---보류-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>서구 - 보류</a></span></li></ul></li><li><span><a href="#전남" data-toc-modified-id="전남-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>전남</a></span><ul class="toc-item"><li><span><a href="#곡성" data-toc-modified-id="곡성-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>곡성</a></span></li><li><span><a href="#순천시" data-toc-modified-id="순천시-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>순천시</a></span></li><li><span><a href="#해남군" data-toc-modified-id="해남군-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>해남군</a></span></li></ul></li><li><span><a href="#충청남도" data-toc-modified-id="충청남도-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>충청남도</a></span><ul class="toc-item"><li><span><a href="#부여군" data-toc-modified-id="부여군-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>부여군</a></span></li><li><span><a href="#서산시" data-toc-modified-id="서산시-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>서산시</a></span></li><li><span><a href="#홍성군" data-toc-modified-id="홍성군-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>홍성군</a></span></li><li><span><a href="#당진시" data-toc-modified-id="당진시-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>당진시</a></span></li><li><span><a href="#아산시" data-toc-modified-id="아산시-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>아산시</a></span></li><li><span><a href="#공주시" data-toc-modified-id="공주시-5.6"><span class="toc-item-num">5.6&nbsp;&nbsp;</span>공주시</a></span></li><li><span><a href="#보령시" data-toc-modified-id="보령시-5.7"><span class="toc-item-num">5.7&nbsp;&nbsp;</span>보령시</a></span></li></ul></li><li><span><a href="#충청북도" data-toc-modified-id="충청북도-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>충청북도</a></span></li><li><span><a href="#전체-데이터-합치기" data-toc-modified-id="전체-데이터-합치기-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>전체 데이터 합치기</a></span></li></ul></div>

## 부산

In [1]:
import pandas as pd
import os

In [2]:
# 부산 데이터프레임
busan_df = pd.DataFrame({'State':[], 'City':[], 'cnt':[], '기준일':[]})
busan_df

Empty DataFrame
Columns: [State, City, cnt, 기준일]
Index: []

### 동구

In [3]:
d_df = pd.read_csv('./mydata/busan_rowcount/donggu.csv', encoding='cp949')
d_df

,등록구,관리기관,관리번호,설치일자,설치장소,설치구분,색상,등주형식,등주형상,등주재질,등주높이
0,동구,동구,79-17,,동구 초량동 653-3번지 일원,가로등,명회색,1등용,원형,주철,9.0
1,동구,동구,79-16,,동구 초량동 653-3번지 일원,가로등,명회색,1등용,원형,주철,9.0
2,동구,동구,79-15,,동구 초량동 653-3번지 일원,가로등,명회색,1등용,원형,주철,9.0
3,동구,동구,79-14,,동구 초량동 653-3번지 일원,가로등,명회색,1등용,원형,주철,9.0
4,동구,동구,79-13,,동구 초량동 653-3번지 일원,가로등,명회색,1등용,원형,주철,9.0
...,...,...,...,...,...,...,...,...,...,...,...
2895,동구,동구 도시국 도시안전과,01월 05일,1986-11-18,상해문 주변,가로등,회색,1등용,팔각,FRP,8.5
2896,동구,동구 도시국 도시안전과,01월 04일,1986-11-18,상해문 주변,가로등,회색,2등용,팔각,SUS,9.5
2897,동구,동구 도시국 도시안전과,01월 03일,1986-11-18,상해문 주변,가로등,회색,2등용,팔각,FRP,9.5
2898,동구,동구 도시국 도시안전과,01월 02일,1986-11-18,부산역 건너편 기업은행 앞,가로등,회색,2등용,원형,원형철주,9.5
2899,동구,동구 도시국 도시안전과,01월 01일,2012-11-14,부산역 건너편 기업은행 앞,가로등,회색,2등용,원형,원형철주,9.5

In [4]:
d_count = d_df.shape[0]
d_count

2900

In [5]:
dong_df = pd.DataFrame({'State':['부산광역시'], 'City':['동구'], 'cnt':[d_count], '기준일':None})
dong_df

   State City   cnt   기준일
0  부산광역시   동구  2900  None

### 동래구

In [6]:
dr_df = pd.read_csv('./mydata/busan_rowcount/dongraegu.csv', encoding='cp949')
dr_df

,관리기관,설치장소,설치개수,설치구분,ARM길이,ARM형태,ARM재질,등주형상,등주형식,등주높이,등주재질,등기구(규격),등기구(개수),램프(규격),램프(개수),안정기(규격),안정기(개수)
0,부산광역시 동래구청,부산광역시 동래구 온천동 473-10,1,가로등,1.8~1.8,사각형,철팔각,팔각,1등용,8.5~8.5,철팔각,사각형,1.0,고압NT(NH형)220V/250W,1.0,고압NT(CC형)220V/250W,1.0
1,부산광역시 동래구청,부산광역시 동래구 온천동 473-8,1,가로등,1.8~1.8,사각형,철팔각,팔각,1등용,8.5~8.5,철팔각,사각형,1.0,고압NT(NH형)220V/250W,1.0,고압NT(CC형)220V/250W,1.0
2,부산광역시 동래구청,부산광역시 동래구 온천동 450-8,1,가로등,1.8~1.8,사각형,철팔각,팔각,1등용,8.5~8.5,철팔각,사각형,1.0,고압NT(NH형)220V/250W,1.0,고압NT(CC형)220V/250W,1.0
3,부산광역시 동래구청,부산광역시 동래구 온천동 183-3,1,가로등,1.8~1.8,사각형,주철,원형,1등용,8.5~8.5,주철,사각형,1.0,메탈(고효율200w),1.0,메탈(고효율200w),1.0
4,부산광역시 동래구청,부산광역시 동래구 온천동 452-16,1,가로등,1.8~1.8,사각형,철팔각,팔각,1등용,8.5~8.5,철팔각,사각형,1.0,고압NT(NH형)220V/250W,1.0,고압NT(CC형)220V/250W,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4527,부산광역시 동래구청,부산광역시 동래구,1,가로등,0~0,NaN,NaN,NaN,1등용,0~0,NaN,100W,1.0,NaN,NaN,NaN,NaN
4528,부산광역시 동래구청,부산광역시 동래구,1,가로등,0~0,NaN,NaN,NaN,1등용,0~0,NaN,100W,1.0,NaN,NaN,NaN,NaN
4529,부산광역시 동래구청,부산광역시 동래구,1,가로등,0~0,NaN,NaN,NaN,1등용,0~0,NaN,100W,1.0,NaN,NaN,NaN,NaN
4530,부산광역시 동래구청,부산광역시 동래구,1,가로등,0~0,NaN,NaN,NaN,1등용,0~0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4531,부산광역시 동래구청,부산광역시 동래구,1,가로등,0~0,NaN,NaN,NaN,1등용,0~0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
dr_count = dr_df.shape[0]
dr_count

4532

In [8]:
dongrae_df = pd.DataFrame({'State':['부산광역시'], 'City':['동래구'], 'cnt':[dr_count], '기준일':None})
dongrae_df

   State City   cnt   기준일
0  부산광역시  동래구  4532  None

In [9]:
busan_df = pd.concat([dong_df, dongrae_df])
busan_df

   State City   cnt   기준일
0  부산광역시   동구  2900  None
0  부산광역시  동래구  4532  None

### 북구

In [10]:
b_df = pd.read_csv('./mydata/busan/bukgu.csv', encoding='cp949')
b_df

     구분        노선별                       구간   조명등 개수
0    일반       강변대로            산업인력공단-구남초교맞은편     216
1    일반       금곡대로                덕천역-호표경계지점      85
2    일반       낙동대로                   덕천역-북구청     204
3    일반       만덕대로                 덕천역-만덕2터널     150
4    일반       백양대로                 덕천역-현대아파트       2
..  ...        ...                       ...     ...
57  LED   효열로235번길         부산은행 금곡동지점~금창초등학교       9
58  LED   덕천로276번길       백양산동문굿모닝힐 121동~204동      37
59  LED  함박봉로140번길  만덕119안전센터(예정)~부산시보건환경연구원      42
60  LED        사상로                 구포삼거리~북구청      27
61  LED  금곡대로550번길             금곡주공7단지~햇빛유치원       8

[62 rows x 4 columns]

In [11]:
b_cnt = b_df['조명등 개수'].sum()
b_cnt

4521

In [12]:
buck_df = pd.DataFrame({'State':['부산광역시'], 'City':['북구'], 'cnt':[b_cnt], '기준일':None})
buck_df

   State City   cnt   기준일
0  부산광역시   북구  4521  None

### 강서구

In [13]:
gs_df = pd.read_csv('./mydata/busan/gangseogu.csv', encoding='cp949')
gs_df

    연번     도로명    등수
0    1     공항로  1055
1    2    가락대로  1149
2    3    낙동남로   705
3    4    낙동북로   363
4    5     생곡로   347
5    6    신항남로   130
6    7    녹산산단  1835
7    8    신호산단   623
8    9  명지오션시티   712
9   10    지사단지  1052
10  11    미음산단   904
11  12    생곡산단   163
12  13    명지국제  1507
13  14    기타도로  9078

In [14]:
gs_cnt = gs_df['등수'].sum()
gs_cnt

19623

In [15]:
gangseo_df = pd.DataFrame({'State':['부산광역시'], 'City':['강서구'], 'cnt':[gs_cnt], '기준일':None})
gangseo_df

   State City    cnt   기준일
0  부산광역시  강서구  19623  None

### 진구

In [16]:
j_df = pd.read_csv('./mydata/busan/jingu.csv', encoding='cp949')
j_df

,가로등위치명,설치유형,설치구간,설치등수,관리기관명,관리기관 전화번호,데이터기준일자
0,백양대로,광로 차도등,진양3～신개금LG,480,부산광역시 부산진구청,051-605-4679,2022-10-18
1,중앙대로,광로 차도등,현대자동차㈜~천내과의원,521,부산광역시 부산진구청,051-605-4679,2022-10-18
2,가야대로,광로 차도등,서면교차로~개금지하철,797,부산광역시 부산진구청,051-605-4679,2022-10-18
3,전포대로,광로 차도등,삼전교차로~문전사거리,354,부산광역시 부산진구청,051-605-4679,2022-10-18
4,월드컵대로,광로 차도등,어린이대공원~초읍한신아파트,57,부산광역시 부산진구청,051-605-4679,2022-10-18
...,...,...,...,...,...,...,...
118,전포남북4로,소로 차도등,고려고시학원~정림골프클럽,4,부산광역시 부산진구청,051-605-4679,2022-10-18
119,진경3로,소로 차도등,서면중학교~부전재가노인복지센터,12,부산광역시 부산진구청,051-605-4679,2022-10-18
120,양지4로,소로 차도등,홍제병원~극동빌딩,8,부산광역시 부산진구청,051-605-4679,2022-10-18
121,성북새싹1로,소로 차도등,성북초등학교~승우산업미라니트,4,부산광역시 부산진구청,051-605-4679,2022-10-18
122,기타이면도로,소로 차도등,NaN,657,부산광역시 부산진구청,051-605-4679,2022-10-18

In [17]:
jin_cnt = j_df['설치등수'].sum()
jin_cnt

8258

In [18]:
j_data = j_df.iloc[[1],[6]]
j_data
jin_data = j_data.values[0]
jin_data

array(['2022-10-18'], dtype=object)

In [19]:
jin_df = pd.DataFrame({'State':['부산광역시'], 'City':['진구'], 'cnt':[jin_cnt], '기준일':jin_data})
jin_df

   State City   cnt         기준일
0  부산광역시   진구  8258  2022-10-18

### 중구

In [20]:
ju_df = pd.read_csv('./mydata/busan/joonggu.csv', encoding='cp949')
ju_df

,도로명,위치,가로등_합계,가로등_일반,가로등_고효율_소계,가로등_고효율(LED),가로등_고효율_기타,총등주(본),등주(FRP)(본)
0,부산광역시 중구 충장대로,무역회관앞~동구경계,58,19,39,0,39,58,20
1,부산광역시 중구 대영로,DSEC빌딩~부산터널,69,0,69,69,0,69,0
2,부산광역시 중구 구덕로,옛시청교차로~자갈치공영주차장,69,2,67,53,14,69,1
3,부산광역시 중구 중앙대로,옛시청교차로~영주동조흥은행,111,0,111,0,111,72,0
4,부산광역시 중구 대청로,부산우체국~부민사거리,74,14,60,40,20,74,0
5,부산광역시 중구 대교로,부산대교~부산본부세관,118,112,6,0,6,118,0
6,부산광역시 중구 보수로,자갈치사거리~흑교사거리,126,125,1,0,1,118,8
7,부산광역시 중구 태종로,옛시청교차로~영도대교,18,9,9,0,9,9,0
8,부산광역시 중구 해관로,중부경찰서~부산데파트,44,0,44,44,0,44,0
9,부산광역시 중구 백산길,백산기념관~한국투자증권,16,0,16,16,0,16,0
10,부산광역시 중구 광복중앙로,창선치안센터~부산근대역사관,36,0,36,0,36,18,0
11,부산광역시 중구 흑교로,보수사거리~기업은행,44,0,44,24,20,44,0
12,부산광역시 중구 자갈치로,공영주차장~남포파출소,56,36,20,0,20,56,0
13,부산광역시 중구 중구로,부산은행영주동지점~남포주차빌딩,94,0,94,70,24,94,0
14,부산광역시 중구 자갈치해안로,금양제빙~부산시수협남포동지점,19,5,14,14,0,19,5
15,부산광역시 중구 광복로,부평오거리~국제시장사거리,30,0,30,30,0,15,0
16,부산광역시 중구 광복로,국제시장사거리~옛시청사거리,100,0,100,100,0,50,0
17,부산광역시 중구 망양로,해광고교~초원아파트,46,0,46,46,0,46,0
18,"부산광역시 중구 부평1,2길",부평시장 안,14,6,8,0,8,6,0
19,"부산광역시 중구 초량상,중로",성심소아과~봉래각,22,0,22,1,21,12,0
20,부산광역시 중구 대교로,롯데백화점광복점뒤편~영도대교,20,0,20,0,20,20,0
21,부산광역시 중구 충장대로5번길,KT서부산지사~세관삼거리,21,0,21,0,21,21,0
22,부산광역시 중구 충장대로9번길,한국선원센터~세관삼거리,26,0,26,0,26,26,0
23,부산광역시 중구 동광길,대청로입구~영주시장,61,21,40,0,40,61,3
24,부산광역시 중구 영주로,동남파크앞교차로~중구청앞교차로,48,0,48,26,22,16,0
25,"부산광역시 중구 동영로, 동영로75번길",부산터널삼거리~두원사우나,34,0,34,1,33,34,0
26,부산광역시 중구 40계단길,40계단문화관광테마거리,25,0,25,0,25,25,0
27,부산광역시 중구 망양로 이면도로,"망양로319번길, 383번안길",51,0,51,0,51,0,0
28,부산광역시 중구 복병산체육공원,복병산체육공원,25,0,25,25,0,25,0
29,부산광역시 중구 복병산 배수지체육공원,배수지 체육공원 내 중구관리 가로등,4,0,4,4,0,2,0
30,부산광역시 중구 중구로 이면도로,"중구로62,75번길",82,24,58,0,58,82,0
31,"부산광역시 중구 부평동 3,4가 이면도로","흑교로 17,21,25,31번길",18,0,18,18,0,16,0
32,"부산광역시 중구 보수동 2,3가 이면도로","흑교로 45,51,59,67,71,75,81,87번길",37,0,37,37,0,1,0
33,부산광역시 중구 남포길,엔터테이너거리,9,9,0,0,0,0,0
34,부산광역시 중구 태종로,영도대교입구(백화점 측면),5,5,0,0,0,0,0
35,부산광역시 중구 대교로,부산대교 상부,58,48,10,10,0,0,0
36,부산광역시 중구 중앙대로,중앙대로22,3,2,1,0,1,0,0
37,부산광역시 중구 중구로188번길,영주교회일원,22,5,17,17,0,0,0
38,부산광역시 중구 대청로135번길,40계단문화테마거리,4,4,0,0,0,0,0
39,부산광역시 중구 영주고가교 하부등,영주고가교 교각하부등,2,0,2,2,0,0,0
40,부산광역시 중구 복병산길,복병산길9-13(큰마루터진입로),3,0,3,3,0,0,0
41,부산광역시 중구 용두산공원 밑 체육공원,광복동1가7,4,0,4,4,0,0,0
42,부산광역시 중구 광복로35번길,아리랑거리,51,0,51,51,0,0,0

In [21]:
# add_str = ju_df['도로명'].str.split(' ')

In [22]:
ju_cnt = ju_df['가로등_합계'].sum()
ju_cnt

1777

In [23]:
jung_df = pd.DataFrame({'State':['부산광역시'], 'City':['중구'], 'cnt':[ju_cnt], '기준일':None})
jung_df

   State City   cnt   기준일
0  부산광역시   중구  1777  None

In [24]:
# jung_df['State'] = add_str.str.get(0)
# jung_df['City'] = add_str.str.get(1)

### 기장군

In [25]:
kj_df = pd.read_csv('./mydata/busan/kijanggun.csv', encoding='cp949')
kj_df

,도로명,위치,가로등_합계,가로등_일반,가로등_고효율_(LED),가로등_고효율_기타,총등주(본)
0,부산광역시 기장군 반송로,기장체육관~반송,91,0,71,20,71
1,부산광역시 기장군 정관산업로,곰내터널~계좌터널,315,0,169,146,315
2,부산광역시 기장군 정관중앙로,정관신도시내,78,0,74,4,78
3,부산광역시 기장군 모전로,정관신도시내,20,0,20,0,20
4,부산광역시 기장군 정관2로,정관신도시내,76,0,60,16,76
...,...,...,...,...,...,...,...
87,부산광역시 기장군 청원길,일광면내,105,0,105,0,102
88,부산광역시 기장군 월평1길,정관면내,32,0,32,0,32
89,부산광역시 기장군 안평로,철마면내,21,0,21,0,21
90,부산광역시 기장군 동서길,기장읍내,27,0,27,0,27
91,부산광역시 기장군 철마천로,철마면내,50,0,50,0,50

In [26]:
kj_cnt = kj_df['가로등_합계'].sum()
kj_cnt

11333

In [27]:
kijang_df = pd.DataFrame({'State':['부산광역시'], 'City':['기장군'], 'cnt':[kj_cnt], '기준일':None})
kijang_df

   State City    cnt   기준일
0  부산광역시  기장군  11333  None

### 남구

In [28]:
n_df = pd.read_csv('./mydata/busan/namgu.csv', encoding='cp949')
n_df

       구분   전력(w)    수량
0    나트륨등   150이하   343
1    나트륨등   250이하   567
2   일반메탈등   200이하   583
3   일반메탈등   250이하   694
4   일반메탈등   400이하    35
5   일반메탈등  1000이하    48
6    LED등    50이하   118
7    LED등   100이하  1129
8    LED등   150이하   754
9    LED등   200이하   147
10     기타   150이하    35

In [29]:
# n_df['수량'] = pd.to_numeric(n_df['수량'])

In [30]:
n_cnt = n_df['수량'].sum()
n_cnt

4453

In [31]:
nam_df = pd.DataFrame({'State':['부산광역시'], 'City':['남구'], 'cnt':[n_cnt], '기준일':None})
nam_df

   State City   cnt   기준일
0  부산광역시   남구  4453  None

### 서구

In [32]:
s_df = pd.read_csv('./mydata/busan/seogu.csv', encoding='cp949')
s_df

        관리기관    연번    도로명     등수     데이터기준일자
0   부산광역시 서구   1.0    감천로   79.0  2023-01-13
1   부산광역시 서구   2.0    구덕로  310.0  2023-01-13
2   부산광역시 서구   3.0  까치고개로   61.0  2023-01-13
3   부산광역시 서구   4.0   꽃마을로  117.0  2023-01-13
4   부산광역시 서구   5.0   낙동대로   23.0  2023-01-13
5   부산광역시 서구   6.0    대신로   63.0  2023-01-13
6   부산광역시 서구   7.0    대영로   98.0  2023-01-13
7   부산광역시 서구   8.0    대티로   61.0  2023-01-13
8   부산광역시 서구   9.0    동대로   13.0  2023-01-13
9   부산광역시 서구  10.0    등대로   77.0  2023-01-13
10  부산광역시 서구  11.0    망양로  110.0  2023-01-13
11  부산광역시 서구  12.0   보수대로  248.0  2023-01-13
12  부산광역시 서구  13.0  송도해변로  136.0  2023-01-13
13  부산광역시 서구  14.0    시약로   34.0  2023-01-13
14  부산광역시 서구  15.0    아미로   18.0  2023-01-13
15  부산광역시 서구  16.0  암남공원로  145.0  2023-01-13
16  부산광역시 서구  17.0    옥천로    7.0  2023-01-13
17  부산광역시 서구  18.0    원양로  164.0  2023-01-13
18  부산광역시 서구  19.0  중앙공원로   24.0  2023-01-13
19  부산광역시 서구  20.0    천마로  100.0  2023-01-13
20  부산광역시 서구  21.0   천마산로  120.0  2023-01-13
21  부산광역시 서구  22.0    천해로   22.0  2023-01-13
22  부산광역시 서구  23.0    초장로   17.0  2023-01-13
23  부산광역시 서구  24.0   충무대로  203.0  2023-01-13
24  부산광역시 서구  25.0   해돋이로  115.0  2023-01-13
25  부산광역시 서구  26.0    흑교로    5.0  2023-01-13
26  부산광역시 서구  27.0     기타  478.0  2023-01-13
27       NaN   NaN    NaN    NaN         NaN

In [33]:
s_cnt = s_df['등수'].sum()
s_cnt

2848.0

In [34]:
s_data = s_df.iloc[[1],[4]]
s_data
seo_data = s_data.values[0]
# str(seo_data)
seo_data

array(['2023-01-13'], dtype=object)

In [35]:
seo_df = pd.DataFrame({'State':['부산광역시'], 'City':['서구'], 'cnt':[s_cnt], '기준일':seo_data})
seo_df

   State City     cnt         기준일
0  부산광역시   서구  2848.0  2023-01-13

### 사하구

In [36]:
sa_df = pd.read_csv('./mydata/busan/sahagu.csv', encoding='cp949')
sa_df

      구분    노선별                   구간    등수     데이터기준일자
0     일반   낙동대로        대티터널입구~사상구 경계   233  2022-05-09
1     일반   강변대로      다대동 대아선재~사상구 경계   384  2022-05-09
2     일반    다대로  당리주면센터 삼거리~다대동 대아선제   446  2022-05-09
3     일반    감천로         옥천초교삼거리~서구경계   112  2022-05-09
4     일반    공단로   하단오거리~신평장림산업단지 사거리   125  2022-05-09
5     일반   낙동남로         하단오거리~강서구 경계   118  2022-05-09
6     일반  감천항만로        감천화력 후문~구평방파제   374  2022-05-09
7     일반    신평로           사하초교~경찰기동대    86  2022-05-09
8     일반    대티로            괴정초교~대티고개    19  2022-05-09
9     일반    괴정로    괴정초교~동매교~하단초교 사거리    55  2022-05-09
10    일반   공단대로    장림고개 사거리~신평강변 삼거리   111  2022-05-09
11    일반     기타                 이면도로  3512  2022-05-09
12   LED    옥천로           감천사거리~아미고개    33  2022-05-09
13   LED   낙동대로      을숙도초교 삼거리~사하구청사   170  2022-05-09
14   LED   낙동대로            동아대 일방통행길    35  2022-05-09
15   LED     기타   감천문화마을, 낙동남로1423번길   205  2022-05-09
16  조명타워    NaN                하단오거리     6  2022-05-09
17  조명타워    NaN         을숙도 초등학교 삼거리     6  2022-05-09
18  조명타워    NaN           하남초등학교 오거리     6  2022-05-09
19  조명타워    NaN         국민체육센터 삼거리 앞     6  2022-05-09

In [37]:
sa_cnt = sa_df['등수'].sum()
sa_cnt

6042

In [38]:
sa_data = sa_df.iloc[[1],[4]]
sa_data
saha_data = sa_data.values[0]
# str(seo_data)
saha_data

array(['2022-05-09'], dtype=object)

In [39]:
sa_df = pd.DataFrame({'State':['부산광역시'], 'City':['사하구'], 'cnt':[sa_cnt], '기준일':saha_data})
sa_df

   State City   cnt         기준일
0  부산광역시  사하구  6042  2022-05-09

### 수영구

In [40]:
su_df = pd.read_csv('./mydata/busan/suyunggu.csv', encoding='cp949')
su_df

,관리번호,소속분전함,행정동,노선명,등기구아이디,등기구종류,등기구회사,등 수,램프종류,램프용량(W),등주종류,등주형태,점멸기종류,분기번호,위도,경도
0,KBS조명탑-1,KBS조명탑,남천1동,수영로,1,머스코,NaN,5,MH,1000.0,기타,조명탑,기타,0,35.143849,129.109464
1,감포로-1-1,감포로-1,민락동,감포로,1,컷오프,NaN,1,LED,150.0,기타,철팔각,기타,0,35.167637,129.117875
2,감포로-1-10,감포로-1,민락동,감포로,1,세종로대형,한라,1,LED,100.0,기타,한전취부등,기타,0,35.163838,129.119239
3,감포로-1-11,감포로-1,민락동,감포로,1,컷오프,NaN,1,LED,150.0,기타,철팔각,기타,0,35.163622,129.119302
4,감포로-1-12,감포로-1,민락동,감포로,1,컷오프,NaN,1,LED,150.0,기타,철팔각,기타,0,35.163146,129.119465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,황령산로8-1-5,황령산로8-1_점검,남천1동,황령산로7번길,1,3번,NaN,1,LED,100.0,기타,한전취부등,기타,0,35.147205,129.109290
3876,황령산로8-1-6,황령산로8-1_점검,남천1동,황령산로8번길,1,3번,NaN,1,LED,100.0,기타,한전취부등,기타,0,35.147472,129.109354
3877,황령산로8-1-7,황령산로8-1_점검,남천1동,황령산로8번길,1,3번,NaN,1,LED,100.0,기타,한전취부등,기타,0,35.148106,129.109516
3878,황령산로8-1-8,황령산로8-1_점검,남천1동,황령산로8번길,1,3번,NaN,1,LED,100.0,기타,한전취부등,기타,0,35.148319,129.109590
3879,황령산로8-1-9,황령산로8-1_점검,남천1동,황령산로8번길,1,3번,NaN,1,LED,100.0,기타,한전취부등,기타,0,35.148541,129.109645

In [41]:
su_cnt = su_df['등 수'].sum()
su_cnt

4009

In [42]:
suyung_df = pd.DataFrame({'State':['부산광역시'], 'City':['수영구'], 'cnt':[su_cnt], '기준일':None})
suyung_df

   State City   cnt   기준일
0  부산광역시  수영구  4009  None

### 연재구

In [43]:
y_df = pd.read_csv('./mydata/busan/yeonjaegu.csv', encoding='cp949')
y_df

             도로명                   위치  가로등(등)
0           거제대로       양정(진구경계)~이사벨여고     157
1          월드컵대로       신리삼거리~종합운동장사거리     286
2            연수로   양정(진구경계)~망미(수영구경계)     147
3            반송로            연산로타리~연안교      77
4         아시아드대로          거제삼거리~거성교차로      46
5            명륜로            교육대학앞~세병교      19
6            과정로          과정사거리~망미동경계     322
7           좌수영로            정보화지하차도일원      38
8           중앙대로       양정(진구경계)~교육대학앞     289
9            미남로           법원~법원어귀교차로      35
10           법원로                법조타운내     113
11           고분로          연산로타리~월륜교차로     169
12          쌍미천로              반송로~연산로      88
13           연안로               청담~안락교      28
14           진남로             연수로~진구경계      12
15           시청로           세화아파트~녹음광장      15
16    거제대로74번길 외         충렬공송상현동상~교대역     152
17        거제시장로     부산은행거제동지점~시청뒤녹음광장      54
18         거제천로        양정피렌체아파트~과정교차로     135
19          거평로     거제여자중학교~거제2동우편취급국      12
20     고분로13번길 외            연산로터리~과정교     153
21     과정로93번길 외        과정교차로~망미주공아파트     146
22     교대로11번길 외         교대역1번출구~법원북로     119
23          금련로      배산역3번~부산여자상업고등학교      28
24          금용로       거제여자중학교~탑마트거제리점      25
25          대리로     롯데캐슬앤데시앙101동~봉성교회       8
26         마곡천로           유진모터스~람세스빌라      15
27          배산로         양지빌라~연수로213번길      11
28         배산북로       삼광주택인테리어공사~해인빌라      11
29          봉수로         럭키자동차운전학원~관음사      18
30          세병로    SC은행연산동지점~부산은행연서지점      27
31          신금로     더샵파크시티101동~LG베스트샵      38
32          신촌로      거제현대아파트~시청역이즈팰리스      28
33     쌍미천로7번길 외       연산동우체국~반송로홈플러스     144
34  아시아드대로11번길 외    현대아파트교차로~운동장교차로일대      87
35          안연로           연산교~팀제이티복싱짐      40
36          연동로         LG베스트샵~장안어린이집      30
37          연미로          동덕현대아파트올라가는길       9
38     연수로11번길 외           연제구청~배산역일대      75
39        온천천남로            연안교~부산환경공단      72
40    월드컵대로3번길 외     신리삼거리~아시아드주경기장일대     180
41   중앙대로990번길 외       부산시청~연산역~교대역일대     108
42         중앙천로          부산은행~연산2치안센터      33
43           진남로     KT동부산지사~경동메르빌아파트      15
44          진연로            부산지방경찰청서쪽길      33
45         토곡남로             선문빌라~럭키랜드      11
46          토곡로           동서교회~현대오일뱅크      22
47          토현로            농협토곡지점~토현중      18
48         톳고개로      화신사이버대학교~동서그린아파트      19
49         해맞이로        거제유림아시아드~화신데파트     137
50          화지로   거제2글로벌화임빌~거제4부산정보고교      54
51         황새알로       교대테니스장~거제자이11동앞      14

In [44]:
y_cnt = y_df['가로등(등)'].sum()
y_cnt

3922

In [45]:
yeon_df = pd.DataFrame({'State':['부산광역시'], 'City':['연재구'], 'cnt':[y_cnt], '기준일':None})
yeon_df

   State City   cnt   기준일
0  부산광역시  연재구  3922  None

In [46]:
busan_all_df_merged = pd.concat([dong_df, dongrae_df, buck_df, gangseo_df, jin_df, jung_df, kijang_df, nam_df, sa_df, seo_df, suyung_df, yeon_df])
busan_all_df_merged = busan_all_df_merged.reset_index(drop = True)
busan_all_df_merged

    State City      cnt         기준일
0   부산광역시   동구   2900.0        None
1   부산광역시  동래구   4532.0        None
2   부산광역시   북구   4521.0        None
3   부산광역시  강서구  19623.0        None
4   부산광역시   진구   8258.0  2022-10-18
5   부산광역시   중구   1777.0        None
6   부산광역시  기장군  11333.0        None
7   부산광역시   남구   4453.0        None
8   부산광역시  사하구   6042.0  2022-05-09
9   부산광역시   서구   2848.0  2023-01-13
10  부산광역시  수영구   4009.0        None
11  부산광역시  연재구   3922.0        None

## 서울

In [47]:
seoul_df = pd.DataFrame({'State':[], 'City':[], 'cnt':[], '기준일':[]})
seoul_df

Empty DataFrame
Columns: [State, City, cnt, 기준일]
Index: []

### 광진구

In [48]:
guang_df = pd.read_csv('./mydata/seoul_rowcount/guangjin.csv', encoding='cp949')
guang_df

           관리번호         위도          경도
0      로데오거리1-1  37.539513  127.070008
1     로데오거리1-16  37.540853  127.066288
2        중곡제방길1  37.571695  127.079518
3       중곡제방길10  37.570218  127.079153
4       중곡제방길11  37.570053  127.079086
...         ...        ...         ...
2717  하우스스토리1-5  37.530094  127.089264
2718  하우스스토리1-6  37.529902  127.089319
2719  하우스스토리1-7  37.529831  127.089568
2720  하우스스토리1-8  37.529883  127.090268
2721  하우스스토리1-9  37.530091  127.090447

[2722 rows x 3 columns]

In [49]:
guang_count = guang_df.shape[0]
guang_count

2722

In [50]:
dong_df = pd.DataFrame({'State':['서울특별시'], 'City':['광진구'], 'cnt':[guang_count], '기준일':None})
dong_df

   State City   cnt   기준일
0  서울특별시  광진구  2722  None

### 서대문구

In [51]:
sd_df = pd.read_csv('./mydata/seoul_rowcount/seodaemoon.csv', encoding='cp949')
sd_df

       연 번   건물유형        주  소       위   치        관리번호
0        1  가로등등주    북가좌동 477  북가좌1동주민센터앞      가재울1-1
1        2  가로등등주    북가좌동 477  북가좌1동주민센터앞      가재울1-2
2        3  가로등등주    북가좌동 477  북가좌1동주민센터앞      가재울1-3
3        4  가로등등주    북가좌동 477  북가좌1동주민센터앞      가재울1-4
4        5  가로등등주    북가좌동 477  북가좌1동주민센터앞      가재울1-5
...    ...    ...         ...         ...         ...
3225  3226  가로등등주  홍은동 275-54      슈퍼어빈스앞  홍제천변길 8-16
3226  3227  가로등등주  홍은동 275-54      슈퍼어빈스앞  홍제천변길 8-17
3227  3228  가로등등주  홍은동 275-54      슈퍼어빈스앞  홍제천변길 8-18
3228  3229  가로등등주  홍은동 275-54      슈퍼어빈스앞  홍제천변길 8-19
3229  3230  가로등등주  홍은동 275-54      슈퍼어빈스앞  홍제천변길 8-20

[3230 rows x 5 columns]

In [52]:
sd_count = sd_df.shape[0]
sd_count

3230

In [53]:
seodae_df = pd.DataFrame({'State':['서울특별시'], 'City':['서대문구'], 'cnt':[sd_count], '기준일':None})
seodae_df

   State  City   cnt   기준일
0  서울특별시  서대문구  3230  None

### 용산

In [54]:
ys_df = pd.read_csv('./mydata/seoul_rowcount/yongsan.csv', encoding='cp949')
ys_df

,등 종류,관리번호,서울특별시 용산구 새주소,설치일자,경도(GPS),위도(GPS)
0,가로등,한강진길1-000,NaN,2016-07-05,127.006976,37.528902
1,가로등,다산로1-001,서울특별시 용산구 한남대로40길 85,2016-01-15,127.002693,37.545558
2,가로등,백범로1-001,서울특별시 용산구 청파로 195,2016-01-18,126.970477,37.536882
3,가로등,두텁바윗길1-001,서울특별시 용산구 소월로2다길 23,2016-01-18,126.978694,37.553865
4,가로등,용호로1-1,서울특별시 용산구 이촌로 1,2016-01-18,126.955254,37.531597
...,...,...,...,...,...,...
3600,가로등,한강대로104길1-025,NaN,2016-05-19,126.972800,37.551384
3601,가로등,한강대로104길1-026,NaN,2016-05-19,126.972568,37.551384
3602,가로등,교각등,NaN,2018-12-12,127.010170,37.529920
3603,가로등,NaN,서울특별시 용산구 소월로 168,2016-01-14,126.984185,37.547922
3604,가로등,두텁바위로 신흥길,서울특별시 용산구 소월로 168,2016-01-14,126.984163,37.547825

In [55]:
ys_count = ys_df.shape[0]
ys_count

3605

In [56]:
yong_df = pd.DataFrame({'State':['서울특별시'], 'City':['용산구'], 'cnt':[ys_count], '기준일':None})
yong_df

   State City   cnt   기준일
0  서울특별시  용산구  3605  None

### 도봉구

In [57]:
db_df = pd.read_csv('./mydata/seoul/dobong.csv', encoding='cp949')
db_df

      시설명  차도등(개)  보행등(개)  지하차도등(개)  교부하부등(개)  분전함(개)      데이터기준일
0  가로등 현황    3439     627       266        40     195  2018-01-01

In [58]:
db_count = db_df['보행등(개)'].values[0]
db_count

627

In [59]:
db_data = db_df.iloc[[0],[6]]
db_data
db_data = db_data.values[0]
# str(seo_data)
db_data

array(['2018-01-01'], dtype=object)

In [60]:
dobong_df = pd.DataFrame({'State':['서울특별시'], 'City':['도봉구'], 'cnt':[db_count], '기준일':db_data})
dobong_df

   State City  cnt         기준일
0  서울특별시  도봉구  627  2018-01-01

### 동대문

In [61]:
ddm_df = pd.read_csv('./mydata/seoul/dongdaemoon.csv', encoding='cp949')
ddm_df

,도로구분,노선명,주소,구간,차도등,보행등,지하차도등,지하보도등,관리기관명,데이터기준일자
0,시도,청계천로,서울특별시 동대문구 청계천로,난계로~신답철교,70.0,11.0,NaN,NaN,서울특별시청,2022-01-01
1,시도,왕산로,서울특별시 동대문구 왕산로,신설동R~시조사,398.0,200.0,NaN,NaN,서울특별시청,2022-01-01
2,시도,천호대로,서울특별시 동대문구 천호대로,신설동R~군자교,266.0,219.0,NaN,NaN,서울특별시청,2022-01-01
3,시도,고산자로,서울특별시 동대문구 고산자로,고산자교~고려대역,161.0,105.0,NaN,NaN,서울특별시청,2022-01-01
4,시도,망우로,서울특별시 동대문구 망우로,시조사~중랑교,158.0,100.0,NaN,NaN,서울특별시청,2022-01-01
5,시도,난계로,서울특별시 동대문구 난계로,황학교~대광중고앞,21.0,17.0,NaN,NaN,서울특별시청,2022-01-01
6,시도,제기로,서울특별시 동대문구 제기로,고대앞~떡전교사거리,142.0,101.0,NaN,NaN,서울특별시청,2022-01-01
7,시도,전농로,서울특별시 동대문구 전농로,떡전교사거리~답십리역,207.0,152.0,NaN,NaN,서울특별시청,2022-01-01
8,시도,서울시립대로,서울특별시 동대문구 서울시립대로,태양A앞R~시립대앞R,138.0,95.0,NaN,NaN,서울특별시청,2022-01-01
9,시도,한천로,서울특별시 동대문구 한천로,도시철도공사R~코롱A앞,369.0,232.0,NaN,NaN,서울특별시청,2022-01-01
10,시도,사가정로,서울특별시 동대문구 사가정로,신답역R~장안교,234.0,178.0,NaN,NaN,서울특별시청,2022-01-01
11,시도,이문로,서울특별시 동대문구 이문로,시조사~이문로54길,163.0,97.0,NaN,NaN,서울특별시청,2022-01-01
12,시도,무학로,서울특별시 동대문구 무학로,무학교~안암오거리,98.0,75.0,NaN,NaN,서울특별시청,2022-01-01
13,시도,회기로,서울특별시 동대문구 회기로,고려대~회기역,132.0,103.0,NaN,NaN,서울특별시청,2022-01-01
14,시도,답십리로,서울특별시 동대문구 답십리로,성바오로병원R~장평교,228.0,183.0,NaN,NaN,서울특별시청,2022-01-01
15,시도,안암로,서울특별시 동대문구 안암로,대광고교R~고려대역,82.0,63.0,NaN,NaN,서울특별시청,2022-01-01
16,시도,겸재로,서울특별시 동대문구 겸재로,휘경여중R~겸재교,34.0,28.0,NaN,NaN,서울특별시청,2022-01-01
17,시도,장한로,서울특별시 동대문구 장한로,장한평역~장안동삼거리,178.0,96.0,NaN,NaN,서울특별시청,2022-01-01
18,구도,장안벚꽃로,서울특별시 동대문구 장안벚꽃로,군자지하차도~장안지하차도,254.0,118.0,278.0,15.0,서울특별시 동대문구청,2022-01-01
19,구도,정릉천동로,서울특별시 동대문구 정릉천동로,정릉천교~제기로,93.0,61.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
20,구도,황물로,서울특별시 동대문구 황물로,답십리굴다리~자동차부품상가,121.0,94.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
21,구도,휘경로,서울특별시 동대문구 휘경로,외국어대학교앞~한천로,67.0,40.0,150.0,NaN,서울특별시 동대문구청,2022-01-01
22,구도,외대역동로,서울특별시 동대문구 외대역동로,휘경2주민센터~이문고가차도,43.0,22.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
23,구도,장한로12길,서울특별시 동대문구 장한로12길,장한로~장한로12길89,21.0,9.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
24,구도,한천로14길,서울특별시 동대문구 한천로14길,한천로62~장한로12길,21.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
25,구도,화랑로32길,서울특별시 동대문구 화랑로32길,한국예술학교~이문로181,7.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
26,구도,신이문로,서울특별시 동대문구 신이문로,이문삼거리~신이문역,39.0,16.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
27,구도,약령시로,서울특별시 동대문구 약령시로,안암오거리~미주삼거리,72.0,37.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
28,구도,경희대로,서울특별시 동대문구 경희대로,경희대삼거리~경희대,20.0,1.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
29,구도,망우로21길,서울특별시 동대문구 망우로21길,삼육병원앞R~망우로317,12.0,11.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
30,구도,하정로,서울특별시 동대문구 하정로,신설동역8번출구~동대문등기소,11.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
31,구도,천호대로47길,서울특별시 동대문구 천호대로47길,신답초교~신답경남아파트101동,18.0,16.0,28.0,NaN,서울특별시 동대문구청,2022-01-01
32,구도,한천로58길,서울특별시 동대문구 한천로58길,이문파출소~석계초교,63.0,29.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
33,구도,한천로66길,서울특별시 동대문구 한천로66길,동부지하차도~성북구경계,8.0,4.0,308.0,51.0,서울특별시 동대문구청,2022-01-01
34,구도,고산자로28길,서울특별시 동대문구 고산자로28길,동대문홈플러스~동대문구청,7.0,6.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
35,구도,홍릉로,서울특별시 동대문구 홍릉로,청량리역~세종대왕기념관R,90.0,64.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
36,구도,신이문지하보차도,서울특별시 동대문구 신이문지하보차도,이문3동 170~173,8.0,NaN,58.0,8.0,서울특별시 동대문구청,2022-01-01
37,구도,독구말지하보차도,서울특별시 동대문구 독구말지하보차도,이문1동 138~116,8.0,NaN,38.0,NaN,서울특별시 동대문구청,2022-01-01
38,구도,전농로10길,서울특별시 동대문구 전농로10길,답십리2동 110~203,64.0,45.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
39,구도,답십리로56길,서울특별시 동대문구 답십리로56길,답십리로56길,13.0,2.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
40,구도,천호대로45길,서울특별시 동대문구 천호대로45길,신답철교~답십리로,19.0,7.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
41,구도,이문로54길,서울특별시 동대문구 이문로54길,이문로종점~한천로종점,17.0,14.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
42,구도,황물로15길,서울특별시 동대문구 황물로15길,두산A107~전농로4길,9.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
43,구도,장한로18길,서울특별시 동대문구 장한로18길,현대홈타운A120~장안벚꽃길,8.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
44,구도,전농로3길,서울특별시 동대문구 전농로3길,전농로~답십리초교,20.0,20.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
45,구도,사가정로2길,서울특별시 동대문구 사가정로2길,답십리16구역,18.0,18.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
46,구도,사가정로4길,서울특별시 동대문구 사가정로4길,답십리16구역,32.0,32.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
47,구도,청량리역고가차도,서울특별시 동대문구 청량리역고가차도,서울시립대로~청량리역,90.0,45.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
48,구도,경동시장로,서울특별시 동대문구 경동시장로,청과물시장입구~제기로,60.0,37.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
49,구도,답십리로11길,서울특별시 동대문구 답십리로11길,답십리로27~칠보모텔,12.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
50,구도,회기지하보도,서울특별시 동대문구 회기지하보도,외대역동로5길~회기로31길,NaN,NaN,NaN,33.0,서울특별시 동대문구청,2022-01-01
51,구도,답십리로35길,서울특별시 동대문구 답십리로35길,답십리로~시립대로12길,22.0,15.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
52,구도,시립대로12길,서울특별시 동대문구 시립대로12길,서울시립대로~사가정로,17.0,12.0,NaN,NaN,서울특별시 동대문구청,2022-01-01
53,구도,왕산로26길,서울특별시 동대문구 왕산로26길,정릉천동로~롯데캐슬(아),8.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01
54,구도,답십리로45길,서울특별시 동대문구 답십리로45길,답십리18구역,13.0,NaN,NaN,NaN,서울특별시 동대문구청,2022-01-01

In [62]:
ddm_count = ddm_df['보행등'].sum()
ddm_count

2830.0

In [63]:
ddm_data = ddm_df.iloc[[0],[9]]
ddm_data
ddm_data = ddm_data.values[0]
# str(seo_data)
ddm_data

array(['2022-01-01'], dtype=object)

In [64]:
dongdae_df = pd.DataFrame({'State':['서울특별시'], 'City':['동대문구'], 'cnt':[ddm_count], '기준일':ddm_data})
dongdae_df

   State  City     cnt         기준일
0  서울특별시  동대문구  2830.0  2022-01-01

### 동작구

In [65]:
dj_df = pd.read_csv('./mydata/seoul/dongjack.csv', encoding='cp949')
dj_df

         표찰번호        지번주소        설치일자 등주형태    램프종류  총등수
0     13-3018   대방동 407-9  2020-10-30  한전주  LED일체형    1
1     13-3024   대방동 407-9  2020-10-30  한전주  LED일체형    1
2     13-3089   대방동 408-2  2020-10-30  한전주  LED일체형    1
3     13-3090  대방동 407-28  2020-10-30  한전주  LED일체형    1
4     13-3095   대방동 408-1  2020-10-30  한전주  LED일체형    1
...       ...         ...         ...  ...     ...  ...
3155  흑석한강로61   흑석동 335-4  2016-12-14  철제주     메탈등    1
3156  흑석한강로62   흑석동 335-4  2016-12-14  철제주     메탈등    1
3157  흑석한강로63   흑석동 335-4  2016-12-14  철제주     메탈등    1
3158  흑석한강로64   흑석동 335-4  2016-12-14  철제주     메탈등    1
3159  흑석한강로65   흑석동 335-4  2016-12-14  철제주  LED일체형    1

[3160 rows x 6 columns]

In [66]:
dj_count = dj_df['총등수'].sum()
dj_count

5205

In [67]:
dongjack_df = pd.DataFrame({'State':['서울특별시'], 'City':['동대문구'], 'cnt':[dj_count], '기준일':None})
dongjack_df

   State  City   cnt   기준일
0  서울특별시  동대문구  5205  None

### 관악구

In [68]:
ga_df = pd.read_csv('./mydata/seoul/guanack.csv', encoding='cp949')
ga_df

    자치구      노선명                구간  2022년도 등주수량(본)
0   관악구     과천대로           사당역~남태령              75
1   관악구     시흥대로       구로공단역- 시흥IC              57
2   관악구      관악로        서울대정문~봉천고개             215
3   관악구      신림로       서울대정문~당곡사거리             220
4   관악구     보라매로       당곡사거리~삼육재활원              32
5   관악구      은천로   은천길삼거리~은천길입구삼거리             124
6   관악구     쑥고개로         관악구청~신림2교              86
7   관악구      문성로         신림1교~미성초교             100
8   관악구      신사로          도림교~시흥대로              77
9   관악구      난곡로          신대방역~호암길             271
10  관악구    남부순환로          사당역~시흥IC             490
11  관악구      양녕로   동작구 경계 ~ 구암초교 앞              91
12  관악구      호암로          산복터널~신림로             165
13  관악구      봉천로          인헌동~클린센터             260
14  관악구      봉천로          인헌동~원당초교              46
15  관악구      관천로          신림1교~도림교             103
16  관악구      원신길       동마아파트 ~ 원신길              12
17  관악구     낙성대로     남부순환로 ~ 서울대후문              61
18  관악구    조원중앙로         구로전화국~도림천              23
19  관악구      조원로        시흥대로 ~ 도림천              62
20  관악구   관악로40길          봉천3동~상도동              16
21  관악구      솔밭로     낙성대역 ~ 장미원아파트              14
22  관악구  낙성대로15길    서울대교수아파트~인헌아파트              25
23  관악구      광신길             신림10동              19
24  관악구      성현로          봉현초교~양녕로             106
25  관악구      구암길        드림타운남문~성현로              31
26  관악구  은천로25가길     드림타운정문~드림타운남문              28
27  관악구   은천로33길        성현로~드림타운정문               8
28  관악구   관악로30길   우성아파트입구~푸르지오아파트              65
29  관악구      승방길        별장아파트~과천대로              25
30  관악구      남현길          공원~선양부동산               9
31  관악구      청룡길         풍림아파트(양측)               7
32  관악구    행운10길  행운동 관악산푸르지오아파트 앞              11
33  관악구      참숯길    서울대입구 e편한세상아파트              80
34  관악구   관악로37길       브라운스톤 아파트 앞              12

In [69]:
ga_count = ga_df['2022년도 등주수량(본)'].sum()
ga_count

3026

In [70]:
gwan_df = pd.DataFrame({'State':['서울특별시'], 'City':['관악구'], 'cnt':[ga_count], '기준일':None})
gwan_df

   State City   cnt   기준일
0  서울특별시  관악구  3026  None

### 광진구

In [71]:
guj_df = pd.read_csv('./mydata/seoul/guangjingu.csv', encoding='cp949')
guj_df

,도로구분,노선명,주소,구간,평균조도(LX),차도등 개수,보행등 개수,지하 차도등 개수,지하 보도등 개수,관리기관명,데이터작성기준일
0,시도,천호대로,서울특별시 광진구 천호대로,천호대로 북단-군자교 동쪽,22,250.0,238.0,NaN,NaN,서울특별시청,2022-02-12
1,시도,아차산로,서울특별시 광진구 아차산로,동일로 ~ 올림픽대교 북단,22,338.0,227.0,NaN,NaN,서울특별시청,2022-02-12
2,시도,아차산로,서울특별시 광진구 아차산로,올림픽대교북단 ~ 구리시계,22,90.0,67.0,NaN,NaN,서울특별시청,2022-02-12
3,시도,동일로,서울특별시 광진구 동일로,영동대교 북단 ~ 중량구계,22,176.0,168.0,NaN,NaN,서울특별시청,2022-02-12
4,시도,답십리로,서울특별시 광진구 답십리로,동일로 ~ 용마산로,22,16.0,NaN,NaN,NaN,서울특별시청,2022-02-12
5,시도,용마산로,서울특별시 광진구 용마산로,답십리로 ~ 천호대로,22,138.0,55.0,NaN,NaN,서울특별시청,2022-02-12
6,시도,광나루로,서울특별시 광진구 광나루로,올림픽대로 ~ 동일로,22,237.0,208.0,NaN,NaN,서울특별시청,2022-02-12
7,시도,능동로,서울특별시 광진구 능동로,뚝섬유원지역 ~ 용마산로,22,293.0,245.0,NaN,NaN,서울특별시청,2022-02-12
8,시도,자양로,서울특별시 광진구 자양로,잠실대교북단 ~ 아차산역사거리,22,157.0,146.0,NaN,NaN,서울특별시청,2022-02-12
9,시도,뚝섬로,서울특별시 광진구 뚝섬로,동일로 ~ 자양로,20,124.0,118.0,NaN,NaN,서울특별시청,2022-02-12
10,시도,면목로,서울특별시 광진구 면목로,군자로 ~ 답십리로,20,73.0,NaN,NaN,NaN,서울특별시청,2022-02-12
11,시도,강변역로,서울특별시 광진구 강변역로,아차산로 ~ 강변북로,22,90.0,46.0,NaN,NaN,서울특별시청,2022-02-12
12,시도,구천면로,서울특별시 광진구 구천면로,아차산로 ~ 강변북로,22,12.0,NaN,NaN,NaN,서울특별시청,2022-02-12
13,시도,군자로,서울특별시 광진구 군자로,화양삼거리 ~ 애플마트,20,33.0,NaN,NaN,NaN,서울특별시청,2022-02-12
14,구도,강변역로4길,서울특별시 광진구 강변역로4길,동서울터미널 외곽,22,47.0,21.0,NaN,NaN,서울특별시 광진구청,2022-02-12
15,구도,광나루로56길,서울특별시 광진구 광나루로56길,테크노마트(강변역로)~광남중학교,22,39.0,27.0,NaN,NaN,서울특별시 광진구청,2022-02-12
16,구도,광장로,서울특별시 광진구 광장로,워커힐로 ~ 천호대로(파리바게트),20,30.0,5.0,24.0,25.0,서울특별시 광진구청,2022-02-12
17,구도,구의강변로,서울특별시 광진구 구의강변로,구의빗물펌프장 ~ 구의삼성쉐르빌,22,31.0,29.0,NaN,NaN,서울특별시 광진구청,2022-02-12
18,구도,구의로,서울특별시 광진구 구의로,GS25 ~ 광나루로(삼화페인트),20,23.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
19,구도,군자로,서울특별시 광진구 군자로,화양삼거리 ~ 천호대로,20,14.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
20,구도,군자로10길,서울특별시 광진구 군자로10길,두산위브아파트 ~ 천호대로,20,7.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
21,구도,긴고랑로,서울특별시 광진구 긴고랑로,동곡삼거리 ~ 중곡삼거리,22,85.0,76.0,NaN,NaN,서울특별시 광진구청,2022-02-12
22,구도,긴고랑로,서울특별시 광진구 긴고랑로,용마산로 ~ 긴고랑로 끝,20,43.0,30.0,NaN,NaN,서울특별시 광진구청,2022-02-12
23,구도,대학문화의거리,서울특별시 광진구 대학문화의거리,능동로 ~ 동일로(능동로17길 포함),20,66.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
24,구도,뚝섬로34길,서울특별시 광진구 뚝섬로34길,"이튼타워, 트라팰리스",15,67.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
25,구도,뚝섬로52길,서울특별시 광진구 뚝섬로52길,뚝섬로 ~ 자양빗물펌프장,20,11.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
26,구도,자양로13길,서울특별시 광진구 자양로13길,뚝섬로 ~ 자양로,20,36.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
27,구도,뚝섬로64길,서울특별시 광진구 뚝섬로64길,하우스스토리 주변,15,17.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
28,구도,로데오거리,서울특별시 광진구 로데오거리,능동로 ~ 아차산로26길,15,15.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
29,구도,아차산로36길,서울특별시 광진구 아차산로36길,스타시티 배후도로,20,14.0,12.0,NaN,NaN,서울특별시 광진구청,2022-02-12
30,구도,능동로10길,서울특별시 광진구 능동로10길,스타시티 배후도로 (광진문화회관),20,16.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
31,구도,아차산로70길,서울특별시 광진구 아차산로70길,아차산로 ~ 광남고등학교,20,36.0,13.0,NaN,NaN,서울특별시 광진구청,2022-02-12
32,구도,아차산로75길,서울특별시 광진구 아차산로75길,아차산로 ~ 광장중학교 가는길,15,12.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
33,구도,아차산로76길,서울특별시 광진구 아차산로76길,아차산로 ~ 구천면로,15,7.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
34,구도,아차산로78길,서울특별시 광진구 아차산로78길,아차산로76길 ~ 정보도서관,15,30.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
35,구도,영화사로,서울특별시 광진구 영화사로,뚜레주르신성중곡점 ~ 아차산생태공원,15,69.0,48.0,NaN,NaN,서울특별시 광진구청,2022-02-12
36,구도,용마산로23길,서울특별시 광진구 용마산로23길,용마산로 ~ 능동로(중곡역1번출구),15,9.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
37,구도,워커힐로,서울특별시 광진구 워커힐로,광나루로 ~ 워커힐 후문,15,100.0,112.0,NaN,NaN,서울특별시 광진구청,2022-02-12
38,구도,자양번영로,서울특별시 광진구 자양번영로,아차산로 ~ 강변북로,20,43.0,42.0,NaN,NaN,서울특별시 광진구청,2022-02-12
39,구도,천호대로140길,서울특별시 광진구 천호대로140길,천호대로 ~ 양진초교,15,10.0,NaN,NaN,NaN,서울특별시 광진구청,2022-02-12
40,구도,중곡제방길,서울특별시 광진구 중곡제방길,중곡빗물펌프장 ~ 장평교 교차로,20,NaN,60.0,NaN,NaN,서울특별시 광진구청,2022-02-12

In [72]:
guj_count = guj_df['보행등 개수'].sum()
guj_count

1993.0

In [73]:
guj_data = guj_df.iloc[[0],[10]]
guj_data = guj_data.values[0]
guj_data

array(['2022-02-12'], dtype=object)

In [74]:
guangj_df = pd.DataFrame({'State':['서울특별시'], 'City':['광진구'], 'cnt':[guj_count], '기준일':guj_data})
guangj_df

   State City     cnt         기준일
0  서울특별시  광진구  1993.0  2022-02-12

### 중랑구

In [75]:
jr_df = pd.read_csv('./mydata/seoul/jungrang.csv', encoding='cp949')
jr_df

   연번  가로등명    개수     데이터기준일자
0   1   차도등  3981  2023-02-14
1   2   보행등  2052  2023-02-14
2   3   육교등    21  2023-02-14
3   4  교량하부   365  2023-02-14

In [76]:
jr_count = jr_df['개수'].sum()
jr_count

6419

In [77]:
jr_data = jr_df.iloc[[0],[3]]
jr_data = jr_data.values[0]
jr_data

array(['2023-02-14'], dtype=object)

In [78]:
joongr_df = pd.DataFrame({'State':['서울특별시'], 'City':['중랑구'], 'cnt':[jr_count], '기준일':jr_data})
joongr_df

   State City   cnt         기준일
0  서울특별시  중랑구  6419  2023-02-14

### 송파구

In [79]:
sp_df = pd.read_csv('./mydata/seoul/songpa.csv', encoding='cp949')
sp_df

,5-1. 노선별 가로등 시설현황(시도),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53
0,"○ [(형태 : 마주보기-A, 지그재그-B, 한쪽-C, 중앙-D) (등주type ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"○ 설치년도,광원,용량,형태,배전방식,등주타입 등이 다를때에는 다음 칸을 이용(같...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"○ 도로연장은 편측설치, 양측설치를 구분하고 실제 도로연장만 기재(가로등 설치연장...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,○ 교량하부등은 각종 하부통과도로 상에 있는 조명을 뜻하며 교량점검용 조명은 제외할 것,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,도로\n구분,노선\n번호,노선명,구 간,노폭\n(m),도로연장(m),NaN,가로등\n설치연장,설치\n년도,조도\n(lx),...,비고,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

사용불가,,,

### 양천구

In [80]:
yc_df = pd.read_csv('./mydata/seoul/yangchun.csv', encoding='cp949')
yc_df

,시군구,도로구분,노선명,구 간,가로등 본수,가로등 등수,비고,데이터기준일자
0,서울특별시 양천구,시도,가로공원길,강서구 경계 ∼부천시계,91,93,NaN,2022-09-30
1,서울특별시 양천구,시도,오목로,남부순환로 ~ 중앙로,62,74,NaN,2022-09-30
2,서울특별시 양천구,시도,오목로,중앙로 ∼ 목동로,59,77,NaN,2022-09-30
3,서울특별시 양천구,시도,오목로,목동로 ∼ 신목로,79,81,NaN,2022-09-30
4,서울특별시 양천구,시도,오목로,목동동로 ∼ 목동서로,12,24,NaN,2022-09-30
...,...,...,...,...,...,...,...,...
85,서울특별시 양천구,구도,신월로20길,신정1-4지구 롯데 주변,32,32,NaN,2022-09-30
86,서울특별시 양천구,구도,목동동로(구도),목동동로~안양천길(유수지길),18,18,NaN,2022-09-30
87,서울특별시 양천구,구도,목동동로12길(신목길),안양천로~신목로,11,11,NaN,2022-09-30
88,서울특별시 양천구,구도,목동동로12길(신목길),신목로~목동동로(목동초교),13,13,NaN,2022-09-30
89,서울특별시 양천구,구도,남부순환로72길,남부순환로~지양로,10,11,NaN,2022-09-30

In [81]:
yc_count = yc_df['가로등 등수'].sum()
yc_count

4836

In [82]:
yc_data = yc_df.iloc[[0],[7]]
yc_data = yc_data.values[0]
yc_data

array(['2022-09-30'], dtype=object)

In [83]:
yangc_df = pd.DataFrame({'State':['서울특별시'], 'City':['양천구'], 'cnt':[yc_count], '기준일':yc_data})
yangc_df

   State City   cnt         기준일
0  서울특별시  양천구  4836  2022-09-30

### 영등포구

In [84]:
ydp_df = pd.read_csv('./mydata/seoul/yungdeungpo.csv', encoding='cp949')
ydp_df

            관리번호                        위치  조명수량     데이터기준일자
0         당산1동-1       서울특별시 영등포구 영신로139-5     1  2022-11-03
1        당산1동-10       서울특별시 영등포구 영등포로28길5     2  2022-11-03
2       당산1동-100       서울특별시 영등포구 당산로20길21     1  2022-11-03
3     당산1동-100-1       서울특별시 영등포구 당산로20길24     1  2022-11-03
4       당산1동-102     서울특별시 영등포구 당산로20길24-2     1  2022-11-03
...          ...                       ...   ...         ...
9004    영등포본동-96       서울특별시 영등포구 영신로20길14     1  2022-11-03
9005    영등포본동-97         서울특별시 영등포구 신길로61길     1  2022-11-03
9006    영등포본동-98       서울특별시 영등포구 신길로61길17     1  2022-11-03
9007    영등포본동-99      서울특별시 영등포구 영신로20가길13     1  2022-11-03
9008        표찰없음  서울특별시 영등포구 여의대방로47가길12-6     1  2022-11-03

[9009 rows x 4 columns]

In [85]:
ydp_count = ydp_df['조명수량'].sum()
ydp_count

9615

In [86]:
ydp_data = ydp_df.iloc[[0],[3]]
ydp_data = ydp_data.values[0]
ydp_data

array(['2022-11-03'], dtype=object)

In [87]:
yeongd_df = pd.DataFrame({'State':['서울특별시'], 'City':['영등포구'], 'cnt':[ydp_count], '기준일':ydp_data})
yeongd_df

   State  City   cnt         기준일
0  서울특별시  영등포구  9615  2022-11-03

In [88]:
seoul_all_df_merged = pd.concat([dong_df, seodae_df, yong_df, dobong_df, dongjack_df, gwan_df, guangj_df, joongr_df, yangc_df, yeongd_df])
seoul_all_df_merged = seoul_all_df_merged.reset_index(drop = True)
seoul_all_df_merged

   State  City     cnt         기준일
0  서울특별시   광진구  2722.0        None
1  서울특별시  서대문구  3230.0        None
2  서울특별시   용산구  3605.0        None
3  서울특별시   도봉구   627.0  2018-01-01
4  서울특별시  동대문구  5205.0        None
5  서울특별시   관악구  3026.0        None
6  서울특별시   광진구  1993.0  2022-02-12
7  서울특별시   중랑구  6419.0  2023-02-14
8  서울특별시   양천구  4836.0  2022-09-30
9  서울특별시  영등포구  9615.0  2022-11-03

# 세종

In [89]:
sej_df = pd.read_csv('./mydata/sejong_rowcount/sj.csv', encoding='cp949')
sej_df

,가로등위치명,설치대수,소재지지번주소,위도,경도,설치형태,관리기관전화번호,관리기관명,데이터기준일자
0,전동면 노장리 609-9,1,전동면 노장리 609-9,36.652672,127.268525,LED,044-301-3735,세종특별자치시청,2022-08-23
1,세종특별자치시 대평동 574-2,1,세종특별자치시 대평동 574-2,36.469947,127.269149,CDM,044-301-3735,세종특별자치시청,2022-08-23
2,전동면 노장리 609-9,1,전동면 노장리 609-9,36.654752,127.268148,LED,044-301-3735,세종특별자치시청,2022-08-23
3,세종특별자치시 대평동 574-2,1,세종특별자치시 대평동 574-2,36.469487,127.268955,CDM,044-301-3735,세종특별자치시청,2022-08-23
4,연기면 산울리 141-3,1,연기면 산울리 141-3,36.529309,127.264695,CDM,044-301-3735,세종특별자치시청,2022-08-23
...,...,...,...,...,...,...,...,...,...
15455,세종특별자치시 나성동 755,1,세종특별자치시 나성동 755,36.492494,127.255561,CDM,044-301-3735,세종특별자치시청,2022-08-23
15456,세종특별자치시 나성동 755,1,세종특별자치시 나성동 755,36.488999,127.255927,CDM,044-301-3735,세종특별자치시청,2022-08-23
15457,세종특별자치시 보람동 633-6,1,세종특별자치시 보람동 633-6,36.480330,127.297978,메탈,044-301-3735,세종특별자치시청,2022-08-23
15458,세종특별자치시 보람동 633-6,1,세종특별자치시 보람동 633-6,36.480591,127.297987,메탈,044-301-3735,세종특별자치시청,2022-08-23
15459,장군면 금암리 342,1,장군면 금암리 342,36.437968,127.217203,LED,044-301-3735,세종특별자치시청,2022-08-23

In [90]:
sej_count = sej_df.shape[0]
sej_count

15460

In [91]:
sej_data = sej_df.iloc[[0],[8]]
sej_data = sej_data.values[0]
sej_data

array(['2022-08-23'], dtype=object)

In [92]:
sejong_all_df_merged = pd.DataFrame({'State':['세종특별자치시'], 'City':[''], 'cnt':[sej_count], '기준일':sej_data})
sejong_all_df_merged

     State City    cnt         기준일
0  세종특별자치시       15460  2022-08-23

## 인천

### 중구

In [93]:
jg_df = pd.read_csv('./mydata/incheon_rowcount/ic_j.csv', encoding='cp949')
jg_df

          순번         분전함    등주         위도          경도     데이터기준일자
0          1  월미로21(YB1)  좌103  37.472676  126.606904  2022-10-12
1          2  월미로21(YB1)  좌104  37.473054  126.606874  2022-10-12
2          3  월미로21(YB1)  좌105  37.473430  126.606698  2022-10-12
3          4  월미로21(YB1)  좌106  37.473816  126.606510  2022-10-12
4          5  월미로21(YB1)  좌107  37.474174  126.606356  2022-10-12
...      ...         ...   ...        ...         ...         ...
15748  15749   흰바위로LP_14    26  37.478098  126.502607  2022-10-12
15749  15750   흰바위로LP_14    27  37.477987  126.502791  2022-10-12
15750  15751   흰바위로LP_14    28  37.477861  126.503011  2022-10-12
15751  15752   흰바위로LP_14    29  37.477743  126.503217  2022-10-12
15752  15753   흰바위로LP_14    30  37.477630  126.503417  2022-10-12

[15753 rows x 6 columns]

In [94]:
jg_count = sd_df.shape[0]
jg_count

3230

In [95]:
jg_data = jg_df.iloc[[0],[5]]
jg_data = jg_data.values[0]
jg_data

array(['2022-10-12'], dtype=object)

In [96]:
joonggu_df = pd.DataFrame({'State':['인천광역시'], 'City':['중구'], 'cnt':[jg_count], '기준일':jg_data})
joonggu_df

   State City   cnt         기준일
0  인천광역시   중구  3230  2022-10-12

### 미추홀구

In [97]:
mch_df = pd.read_csv('./mydata/incheon_rowcount/ic_mch.csv', encoding='cp949')
mch_df

,관리번호,사용목적,소재지도로명주소,소재지지번주소,위도,경도,설치형태,데이터기준일,데이터관리부서
0,2030거리-01,가로등,인천광역시 미추홀구,인천광역시 미추홀구 주안동 167,37.462825,126.681185,LED,2022-08-04,미추홀구 건설과
1,2030거리-02,가로등,인천광역시 미추홀구 미추홀대로 736,인천광역시 미추홀구 주안동 140-5,37.463306,126.680773,LED,2022-08-04,미추홀구 건설과
2,이공삼공거리 #249-01,가로등,인천광역시 미추홀구 미추홀대로734번길 6,인천광역시 미추홀구 주안동 143-3,37.462828,126.680761,LED,2022-08-04,미추홀구 건설과
3,이공삼공거리 #249-02,가로등,인천광역시 미추홀구 주안로104번길 12,인천광역시 미추홀구 주안동 140-7,37.463431,126.681100,LED,2022-08-04,미추홀구 건설과
4,이공삼공거리 #249-03,가로등,인천광역시 미추홀구 주안로104번길 8,인천광역시 미추홀구 주안동 140-4,37.463603,126.681036,LED,2022-08-04,미추홀구 건설과
...,...,...,...,...,...,...,...,...,...
4402,제물포보도육교 #295-03,가로등,인천광역시 미추홀구 경인로 129 제물포 역사,인천광역시 미추홀구 도화동 668,37.466747,126.662527,LED,2022-08-04,미추홀구 건설과
4403,제물포보도육교 #295-04,가로등,인천광역시 미추홀구,인천광역시 미추홀구 도화동 639-1,37.466595,126.662473,LED,2022-08-04,미추홀구 건설과
4404,제물포보도육교 #295-05,가로등,인천광역시 미추홀구 경인로 175-22 패리스빌,인천광역시 미추홀구 도화동 639-4,37.466414,126.662478,LED,2022-08-04,미추홀구 건설과
4405,제물포보도육교 #295-06,가로등,인천광역시 미추홀구 경인로 175-22 패리스빌,인천광역시 미추홀구 도화동 639-4,37.466442,126.662400,LED,2022-08-04,미추홀구 건설과
4406,제물포보도육교 #295-07,가로등,인천광역시 미추홀구,인천광역시 미추홀구 도화동 640-21,37.466427,126.662331,LED,2022-08-04,미추홀구 건설과

In [98]:
mch_count = mch_df.shape[0]
mch_count

4407

In [99]:
mch_data = mch_df.iloc[[0],[7]]
mch_data = mch_data.values[0]
mch_data

array(['2022-08-04'], dtype=object)

In [100]:
michu_df = pd.DataFrame({'State':['인천광역시'], 'City':['미추홀구'], 'cnt':[mch_count], '기준일':mch_data})
michu_df

   State  City   cnt         기준일
0  인천광역시  미추홀구  4407  2022-08-04

### 남동구

In [101]:
nd_df = pd.read_csv('./mydata/incheon/ic_nd.csv', encoding='cp949')
nd_df

,등종류,관리번호,회로,등주수,등수,설치구간 도로명주소,설치구간 지번주소,설치일자,위도,경도,관리기관전화번호,관리기관명,데이터기준일자
0,가로등,간석고가교 L-01,4,30,30,"인천광역시 남동구 백범로 417, (간석동)",인천광역시 남동구 간석동 238-9,2011-05-17,37.467300,126.704774,032-453-2742,남동구청 건설과,2022-08-24
1,가로등,간석지하차도,8,51,51,"인천광역시 남동구 구월로 353, (만수동)",인천광역시 남동구 구월로 353,2012-06-04,37.455330,126.730095,032-453-2742,남동구청 건설과,2022-08-24
2,가로등,간석지하차도1,4,18,36,"인천광역시 남동구 남동대로 935, A동 (간석동, 리더스타워)",인천광역시 남동구 간석동 273-1,2011-05-16,37.465997,126.707487,032-453-2742,남동구청 건설과,2022-08-24
3,가로등,간석지하차도2,1,11,22,"인천광역시 남동구 경인로 648, (간석동)",인천광역시 남동구 간석동 109-5,2012-04-16,37.467609,126.708251,032-453-2742,남동구청 건설과,2022-08-24
4,가로등,걸재천로L-01,4,13,13,"인천광역시 남동구 걸재천로39번길 4-1, 103동 (서창동, 다청림)",인천광역시 남동구 서창동 75-19,2011-04-25,37.434725,126.753143,032-453-2742,남동구청 건설과,2022-08-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...
739,가로등,호구포로R-11,3,11,22,"인천광역시 남동구 호구포로 766, (구월동)",인천광역시 남동구 구월동 1272-12,2012-06-14,37.450751,126.719074,032-453-2742,남동구청 건설과,2022-08-24
740,가로등,호구포로R-12,4,13,26,"인천광역시 남동구 호구포로 812, (구월동)",인천광역시 남동구 구월동 1264-10,2012-11-08,37.454784,126.719582,032-453-2742,남동구청 건설과,2022-08-24
741,가로등,호구포로R-13,4,20,40,"인천광역시 남동구 호구포로 844, (구월동)",인천광역시 남동구 구월동 342-213,2011-05-18,37.457906,126.719992,032-453-2742,남동구청 건설과,2022-08-24
742,가로등,호구포로R-14,4,16,32,"인천광역시 남동구 호구포로 924, (만수동, 햇빛마을벽산아파트)",인천광역시 남동구 만수동 1114,2012-03-18,37.464589,126.724727,032-453-2742,남동구청 건설과,2022-08-24
743,가로등,호구포역길L-01,4,20,22,"인천광역시 남동구 논현고잔로 211-21, (논현동)",인천광역시 남동구 논현동 641-1번지,2012-04-14,37.400605,126.715477,032-453-2742,남동구청 건설과,2022-08-24

In [102]:
nd_count = nd_df['등수'].sum()
nd_count

17820

In [103]:
nd_data = nd_df.iloc[[0],[12]]
nd_data = nd_data.values[0]
nd_data

array(['2022-08-24'], dtype=object)

In [104]:
nd_df = pd.DataFrame({'State':['인천광역시'], 'City':['남동구'], 'cnt':[nd_count], '기준일':nd_data})
nd_df

   State City    cnt         기준일
0  인천광역시  남동구  17820  2022-08-24

### 옹진군

In [105]:
oj_df = pd.read_csv('./mydata/incheon/ic_og.csv', encoding='cp949')
oj_df

,면별,구분,가로등위치명,설치개수,소재지도로명주소,소재지지번주소,설치년도,설치형태,관리기관전화번호,데이터기준일자
0,북도면,신도1번,신도로,11,인천 옹진 북도면 신도리,인천 옹진 북도면 신도리,2017,지주,032-899-2923,2022-04-21
1,북도면,신도2번,노을및 바다 앞,3,인천 옹진 북도면 신도리,인천 옹진 북도면 신도리,2017,지주,032-899-2923,2022-04-21
2,북도면,신도3번,신도로 50번길,6,인천 옹진 북도면 신도리,인천 옹진 북도면 신도리,2017,지주,032-899-2923,2022-04-21
3,북도면,신도4번,신도선착장,8,인천 옹진 북도면 신도리,인천 옹진 북도면 신도리,2017,지주,032-899-2923,2022-04-21
4,북도면,신도5번,신도로,20,인천 옹진 북도면 신도리,인천 옹진 북도면 신도리,2017,지주,032-899-2923,2022-04-21
...,...,...,...,...,...,...,...,...,...,...
162,영흥면,영흥37번,발전소 가는길,17,인천 옹진 영흥면 내리,인천 옹진 영흥면 내리,2017,지주,032-899-2923,2022-04-21
163,영흥면,영흥38번,웰빙해장국 앞,13,인천 옹진 영흥면 내리,인천 옹진 영흥면 내리,2017,지주,032-899-2923,2022-04-21
164,영흥면,영흥39번,십리포주차장 2,13,인천 옹진 영흥면 내리,인천 옹진 영흥면 내리,2017,지주,032-899-2923,2022-04-21
165,영흥면,영흥40번,영흥중학교 아래,6,인천 옹진 영흥면 내리,인천 옹진 영흥면 내리,2017,지주,032-899-2923,2022-04-21
166,영흥면,영흥41번,영흥중학교 가는길,5,인천 옹진 영흥면 내리,인천 옹진 영흥면 내리,2017,지주,032-899-2923,2022-04-21

In [106]:
oj_count = oj_df['설치개수'].sum()
oj_count

2055

In [107]:
oj_data = oj_df.iloc[[0],[9]]
oj_data = oj_data.values[0]
oj_data

array(['2022-04-21'], dtype=object)

In [108]:
ongj_df = pd.DataFrame({'State':['인천광역시'], 'City':['옹진군'], 'cnt':[oj_count], '기준일':oj_data})
ongj_df

   State City   cnt         기준일
0  인천광역시  옹진군  2055  2022-04-21

### 서구 - 보류

In [109]:
seo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   State   1 non-null      object
 1   City    1 non-null      object
 2   cnt     1 non-null      float64
 3   기준일     1 non-null      object
dtypes: float64(1), object(3)
memory usage: 160.0+ bytes

In [110]:
seo_df = pd.read_csv('./mydata/incheon/ic_s.csv', encoding='cp949')
seo_df['sum'] = seo_df['LED30(모갈)'] + seo_df['LED50']  + seo_df['LED60(모갈)'] +  seo_df['LED60'] + seo_df['LED100'] + seo_df['LED150'] + seo_df['LED200'] + seo_df['CDM350'] + seo_df['CDM250'] + seo_df['CDM200'] + seo_df['CDM150'] + seo_df['CDM70'] + seo_df['MH200W'] + seo_df['MH350W'] + seo_df['CMH400W'] +seo_df['M100W'] + seo_df['M175W']

In [111]:
seo_df.fillna(0, inplace=True)
seo_df

,노선명,관리주체,위치명,주소,LED30(모갈),LED50,LED60(모갈),LED60,LED100,LED150,...,CDM250,CDM200,CDM150,CDM70,MH200W,MH350W,CMH400W,M100W,M175W,sum
0,서곶로,시,대인고교앞,공촌동 산30-4,5.0,1.0,0.0,0.0,0.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
1,서곶로,시,시굴집~검암4,검암동 227-6번지,11.0,3.0,0.0,0.0,0.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,봉수대로,시,백석대교,인천종점,0.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0
3,봉수대로,시,백석대교,인천종점,0.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0
4,서곶로,시,백석고교건너,백석동 산25-3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1227,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1228,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1229,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1230,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
seo_df['sum'] = seo_df['LED30(모갈)'] + seo_df['LED50']  + seo_df['LED60(모갈)'] +  seo_df['LED60'] + seo_df['LED100'] + seo_df['LED150'] + seo_df['LED200'] + seo_df['CDM350'] + seo_df['CDM250'] + seo_df['CDM200'] + seo_df['CDM150'] + seo_df['CDM70'] + seo_df['MH200W'] + seo_df['MH350W'] + seo_df['CMH400W'] +seo_df['M100W'] + seo_df['M175W']

In [113]:
seo_df

,노선명,관리주체,위치명,주소,LED30(모갈),LED50,LED60(모갈),LED60,LED100,LED150,...,CDM250,CDM200,CDM150,CDM70,MH200W,MH350W,CMH400W,M100W,M175W,sum
0,서곶로,시,대인고교앞,공촌동 산30-4,5.0,1.0,0.0,0.0,0.0,21.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,29.0
1,서곶로,시,시굴집~검암4,검암동 227-6번지,11.0,3.0,0.0,0.0,0.0,27.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0
2,봉수대로,시,백석대교,인천종점,0.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,30.0
3,봉수대로,시,백석대교,인천종점,0.0,15.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,30.0
4,서곶로,시,백석고교건너,백석동 산25-3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1226,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1227,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1228,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1229,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1230,검단식품산업단지,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [114]:
seo_count = seo_df['sum'].sum()
seo_count

22540.0

In [115]:
seo_df = pd.DataFrame({'State':['인천광역시'], 'City':['서구'], 'cnt':[seo_count], '기준일':None})
seo_df

   State City      cnt   기준일
0  인천광역시   서구  22540.0  None

In [116]:
incheon_all_df_merged = pd.concat([joonggu_df, michu_df, nd_df, ongj_df, seo_df])
incheon_all_df_merged = incheon_all_df_merged.reset_index(drop = True)
incheon_all_df_merged

   State  City      cnt         기준일
0  인천광역시    중구   3230.0  2022-10-12
1  인천광역시  미추홀구   4407.0  2022-08-04
2  인천광역시   남동구  17820.0  2022-08-24
3  인천광역시   옹진군   2055.0  2022-04-21
4  인천광역시    서구  22540.0        None

## 전남

### 곡성

In [117]:
gs_df = pd.read_csv('./mydata/jeonnam_rowcount/jn_gs.csv', encoding='cp949')
gs_df

,관리번호,시도명,시군구명,읍면동명,행정기관코드,계약구분,고객명,소재지도로명주소,소재지지번주소,위도,경도,관리기관명,관리기관전화번호,데이터기준일자
0,GS-1-1,전라남도,곡성군,곡성읍,4672025000,정액제,곡성읍사무소,전라남도 곡성군 곡성읍 교촌죽안길 30-1,전라남도 곡성군 곡성읍 교촌리 101,35.283780,127.286088,전라남도 곡성군청,061-360-8630,2023-02-01
1,GS-1-2,전라남도,곡성군,곡성읍,4672025000,정액제,곡성읍장,전라남도 곡성군 곡성읍 교촌죽안길 36,전라남도 곡성군 곡성읍 교촌리 105,35.283853,127.285675,전라남도 곡성군청,061-360-8630,2023-02-01
2,GS-1-3,전라남도,곡성군,곡성읍,4672025000,정액제,곡성읍장,NaN,전라남도 곡성군 곡성읍 교촌리 109-5,35.284467,127.285257,전라남도 곡성군청,061-360-8630,2023-02-01
3,GS-1-4,전라남도,곡성군,곡성읍,4672025000,정액제,곡성읍사무소,전라남도 곡성군 곡성읍 교촌길 70-3,전라남도 곡성군 곡성읍 교촌리 116-1,35.283942,127.282787,전라남도 곡성군청,061-360-8630,2023-02-01
4,GS-1-5,전라남도,곡성군,곡성읍,4672025000,정액제,곡성읍사무소,NaN,전라남도 곡성군 곡성읍 교촌리 120-1,35.283704,127.283585,전라남도 곡성군청,061-360-8630,2023-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6644,I-2-7,전라남도,곡성군,입면,4672038000,계기판,입면사무소,NaN,전라남도 곡성군 입면 서봉리 697-4,35.311060,127.200246,전라남도 곡성군청,061-360-8630,2023-02-01
6645,I-2-8,전라남도,곡성군,입면,4672038000,계기판,입면사무소,NaN,전라남도 곡성군 입면 송전리 1-306,35.314153,127.200244,전라남도 곡성군청,061-360-8630,2023-02-01
6646,I-2-9,전라남도,곡성군,입면,4672038000,계기판,입면장,NaN,전라남도 곡성군 입면 제월리 164-2,35.324863,127.227535,전라남도 곡성군청,061-360-8630,2023-02-01
6647,JG-2-1,전라남도,곡성군,죽곡면,4672035000,계기판,죽곡면사무소,전라남도 곡성군 죽곡면 섬진강로 1015,전라남도 곡성군 죽곡면 하한리 929-3,35.191792,127.375836,전라남도 곡성군청,061-360-8630,2023-02-01
6648,JG-2-2,전라남도,곡성군,죽곡면,4672035000,계기판,곡성군수,NaN,전라남도 곡성군 죽곡면 태평리 산109-4,35.141566,127.312731,전라남도 곡성군청,061-360-8630,2023-02-01

In [118]:
gs_count = sd_df.shape[0]
gs_count

3230

In [119]:
gs_data = gs_df.iloc[[0],[13]]
gs_data = gs_data.values[0]
gs_data

array(['2023-02-01'], dtype=object)

In [120]:
gock_df = pd.DataFrame({'State':['전라남도'], 'City':['곡성군'], 'cnt':[gs_count], '기준일':gs_data})
gock_df

  State City   cnt         기준일
0  전라남도  곡성군  3230  2023-02-01

### 순천시

In [121]:
sc_df = pd.read_csv('./mydata/jeonnam_rowcount/jn_sc.csv', encoding='cp949')
sc_df

,관리번호,위도,경도,사용목적,소재지도로명주소,소재지지번주소,설치년도,설치형태,데이터 기준일,데이터 관리부서
0,중앙로01-1,34.992943,127.493036,가로등,NaN,전라남도 순천시 서면 동산리 66-8,2014,LED,2021-09-01,순천시 도로과
1,중앙로01-2,34.992601,127.493524,가로등,NaN,전라남도 순천시 서면 동산리 89-10,2014,LED,2021-09-01,순천시 도로과
2,중앙로01-3,34.992235,127.493801,가로등,NaN,전라남도 순천시 서면 동산리 89-10,2014,LED,2021-09-01,순천시 도로과
3,중앙로01-4,34.991892,127.493866,가로등,NaN,전라남도 순천시 가곡동 3-5,2014,LED,2021-09-01,순천시 도로과
4,중앙로01-5,34.991561,127.493968,가로등,NaN,전라남도 순천시 가곡동 3-5,2014,LED,2021-09-01,순천시 도로과
...,...,...,...,...,...,...,...,...,...,...
10720,아교길1-3,34.941942,127.461831,가로등,NaN,전라남도 순천시 와룡동 102-4,2020,LED,2021-09-01,순천시 도로과
10721,NaN,34.955601,127.523868,가로등,NaN,전라남도 순천시 조례동 479-3,2020,LED,2021-09-01,순천시 도로과
10722,NaN,34.955865,127.523793,가로등,NaN,전라남도 순천시 조례동 480-29,2020,LED,2021-09-01,순천시 도로과
10723,NaN,34.956199,127.523675,가로등,NaN,전라남도 순천시 조례동 480-40,2020,LED,2021-09-01,순천시 도로과
10724,NaN,34.956423,127.523509,가로등,NaN,전라남도 순천시 조례동 480-29,2020,LED,2021-09-01,순천시 도로과

In [122]:
sc_count = sc_df.shape[0]
sc_count

10725

In [123]:
sc_data = sc_df.iloc[[0],[8]]
sc_data = sc_data.values[0]
sc_data

array(['2021-09-01'], dtype=object)

In [124]:
sunch_df = pd.DataFrame({'State':['전라남도'], 'City':['순천시'], 'cnt':[sc_count], '기준일':sc_data})
sunch_df

  State City    cnt         기준일
0  전라남도  순천시  10725  2021-09-01

### 해남군

In [125]:
hn_df = pd.read_csv('./mydata/jeonnam_rowcount/jn_hn.csv', encoding='cp949')
hn_df

,보안등위치명,설치개수,소재지도로명주소,소재지지번주소,위도,경도,설치년도,설치형태,관리기관전화번호,관리기관명,데이터기준일자
0,갈두선착장01,1,전라남도 해남군 북일면 금당리 55-2,전라남도 해남군 갈두길 183-31,34.430196,126.685570,2015,전용주,061-530-5878,해남군,2022-05-18
1,갈두선착장02,1,전라남도 해남군 북일면 금당리 55-2,전라남도 해남군 갈두길 183-31,34.429896,126.685417,2015,전용주,061-530-5878,해남군,2022-05-18
2,갈두선착장03,1,전라남도 해남군 북일면 금당리 55-2,전라남도 해남군 갈두길 183-31,34.429578,126.685380,2015,전용주,061-530-5878,해남군,2022-05-18
3,갈두선착장04,1,전라남도 해남군 북일면 금당리 55-2,전라남도 해남군 갈두길 183-31,34.429261,126.685327,2015,전용주,061-530-5878,해남군,2022-05-18
4,갈두선착장05,1,전라남도 해남군 북일면 금당리 55-2,전라남도 해남군 갈두길 183-31,34.428980,126.685164,2015,전용주,061-530-5878,해남군,2022-05-18
...,...,...,...,...,...,...,...,...,...,...,...
1988,황산교차로68,1,전라남도 해남군 현산면 황산리 819-1,전라남도 해남군 현산북평로 583,34.429310,126.574981,2015,전용주,061-530-5878,해남군,2022-05-18
1989,황산교차로69,1,전라남도 해남군 현산면 황산리 819-1,전라남도 해남군 현산북평로 583,34.429588,126.574693,2015,전용주,061-530-5878,해남군,2022-05-18
1990,황산교차로70,1,전라남도 해남군 현산면 황산리 819-1,전라남도 해남군 현산북평로 583,34.429858,126.574407,2015,전용주,061-530-5878,해남군,2022-05-18
1991,황산교차로71,1,전라남도 해남군 현산면 황산리 819-1,전라남도 해남군 현산북평로 583,34.430178,126.574111,2015,전용주,061-530-5878,해남군,2022-05-18
1992,황산교차로72,1,전라남도 해남군 현산면 황산리 819-1,전라남도 해남군 현산북평로 583,34.430415,126.573872,2015,전용주,061-530-5878,해남군,2022-05-18

In [126]:
hn_count = hn_df.shape[0]
hn_count

1993

In [127]:
hn_data = hn_df.iloc[[0],[10]]
hn_data = hn_data.values[0]
hn_data

array(['2022-05-18'], dtype=object)

In [128]:
haen_df = pd.DataFrame({'State':['전라남도'], 'City':['해남군'], 'cnt':[hn_count], '기준일':hn_data})
haen_df

  State City   cnt         기준일
0  전라남도  해남군  1993  2022-05-18

In [129]:
jeonnam_all_df_merged = pd.concat([gock_df, sunch_df, haen_df])
jeonnam_all_df_merged = jeonnam_all_df_merged.reset_index(drop = True)
jeonnam_all_df_merged

  State City    cnt         기준일
0  전라남도  곡성군   3230  2023-02-01
1  전라남도  순천시  10725  2021-09-01
2  전라남도  해남군   1993  2022-05-18

## 충청남도

In [130]:
cn_df = pd.read_csv('./mydata/chungnam/cn.csv', encoding='cp949')
cn_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
0,4125,2,충청남도,부여군,나루터로,충청남도 부여군 부여읍 나루터로 72,충청남도 부여군 부여읍 구교리 420,36.289902,126.907549,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
1,4126,2,충청남도,부여군,부소로,충청남도 부여군 부여읍 부소로 13,충청남도 부여군 부여읍 관북리 165,36.284215,126.912789,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
2,4127,2,충청남도,부여군,정림로,충청남도 부여군 부여읍 정림로 83,충청남도 부여군 부여읍 동남리 412,36.279025,126.912881,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
3,4128,2,충청남도,부여군,계백로,NaN,충청남도 부여군 부여읍 쌍북리 산 31,36.278048,126.922629,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
4,4129,2,충청남도,부여군,신기정로,NaN,충청남도 부여군 부여읍 동남리 174-9,36.271221,126.909165,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,4464,2,충청남도,보령시,두러뫼길,NaN,충청남도 보령시 동대동 658-4,36.354861,126.606714,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
340,4465,2,충청남도,보령시,수로길,NaN,충청남도 보령시 동대동 561-7,36.348267,126.610273,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
341,4466,2,충청남도,보령시,천변남길,NaN,충청남도 보령시 동대동 727-16,36.352458,126.603240,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
342,4467,2,충청남도,보령시,신설1길,충청남도 보령시 신설1길 15,충청남도 보령시 동대동 1956,36.349361,126.604425,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
343,4468,2,충청남도,보령시,됫박산1길,충청남도 보령시 됫박산1길 31,충청남도 보령시 신흑동 1440-49,36.310079,126.520294,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN

부여군, 서산, 홍성군, 당진, 아산, 공주, 보령시

### 부여군

In [131]:
# 충남 전체 데이터에서 부여군 데이터만 뽑아내 데이터프레임만들기
by_df = (cn_df.시군구명 == '부여군')
by_df = cn_df[by_df]
by_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
0,4125,2,충청남도,부여군,나루터로,충청남도 부여군 부여읍 나루터로 72,충청남도 부여군 부여읍 구교리 420,36.289902,126.907549,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
1,4126,2,충청남도,부여군,부소로,충청남도 부여군 부여읍 부소로 13,충청남도 부여군 부여읍 관북리 165,36.284215,126.912789,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
2,4127,2,충청남도,부여군,정림로,충청남도 부여군 부여읍 정림로 83,충청남도 부여군 부여읍 동남리 412,36.279025,126.912881,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
3,4128,2,충청남도,부여군,계백로,NaN,충청남도 부여군 부여읍 쌍북리 산 31,36.278048,126.922629,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
4,4129,2,충청남도,부여군,신기정로,NaN,충청남도 부여군 부여읍 동남리 174-9,36.271221,126.909165,1,...,Y,NaN,NaN,NaN,2019.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
5,4130,2,충청남도,부여군,서동공원 서동문화관앞,충청남도 부여군 부여읍 서동로 84,충청남도 부여군 부여읍 동남리 136-1,36.272301,126.913845,1,...,Y,NaN,NaN,NaN,2020.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
6,4131,2,충청남도,부여군,서동공원 임시주차장,NaN,충청남도 부여군 부여읍 군수리 22-1,36.267975,126.909502,1,...,Y,NaN,NaN,NaN,2020.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
7,4132,2,충청남도,부여군,홍선아파트 앞 공원,충청남도 부여군 부여읍 계백로 418-11,충청남도 부여군 부여읍 쌍북리 730,36.282986,126.923310,1,...,Y,NaN,NaN,NaN,2020.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
8,4133,2,충청남도,부여군,규암 수북정 앞 선착장,NaN,충청남도 부여군 규암면 규암리 152-5,36.274715,126.890465,1,...,Y,NaN,NaN,NaN,2020.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN
9,4134,2,충청남도,부여군,석우리 요트경기장,NaN,충청남도 부여군 규암면 석우리 41-2,36.274021,126.857864,1,...,Y,NaN,NaN,NaN,2020.0,충청남도 부여군청,041-830-2335,2022-07-19,4570000,NaN

In [132]:
by_count = by_df.shape[0]
by_count

10

In [133]:
by_data = by_df.iloc[[0],[-3]]
by_data = by_data.values[0]
by_data

array(['2022-07-19'], dtype=object)

In [134]:
byeo_df = pd.DataFrame({'State':['충청남도'], 'City':['부여군'], 'cnt':[by_count], '기준일':by_data})
byeo_df

  State City  cnt         기준일
0  충청남도  부여군   10  2022-07-19

### 서산시

In [135]:
# 서산시 데이터 프레임 만들기
ss_df = (cn_df.시군구명 == '서산시')
ss_df = cn_df[ss_df]
ss_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
10,4135,1,충청남도,서산시,호수공원1로,충청남도 서산시 호수공원1로 34,충청남도 서산시 예천동 1307,36.772839,126.451886,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
11,4136,1,충청남도,서산시,덕지천로,충청남도 서산시 덕지천로 90,충청남도 서산시 석남동 57-11,36.769546,126.458355,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
12,4137,1,충청남도,서산시,서해로,충청남도 서산시 서해로 3415,충청남도 서산시 석남동 55-1,36.769679,126.458503,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
13,4138,1,충청남도,서산시,서해로,충청남도 서산시 서해로 3415,충청남도 서산시 석남동 55-1,36.769797,126.458617,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
14,4139,1,충청남도,서산시,서해로,충청남도 서산시 서해로 3415,충청남도 서산시 석남동 55-3,36.769965,126.458367,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,4230,1,충청남도,서산시,고운로,충청남도 서산시 고운로 243,충청남도 서산시 동문동 1044-21,36.783886,126.462223,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
106,4231,1,충청남도,서산시,고운로,충청남도 서산시 고운로 242,충청남도 서산시 동문동 1044-21,36.783747,126.462333,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
107,4232,1,충청남도,서산시,고운로,충청남도 서산시 고운로 246,충청남도 서산시 동문동 366-12,36.783944,126.462649,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
108,4233,1,충청남도,서산시,고운로,충청남도 서산시 고운로 246,충청남도 서산시 동문동 1068,36.783805,126.462697,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN
109,4234,1,충청남도,서산시,고운로,충청남도 서산시 고운로 251,충청남도 서산시 동문동 373-3,36.784042,126.462990,1,...,N,가로등제어,상태감시 및 조명제어/길찾기 기능 제공,NaN,2021.0,서산시,041-660-2389,2021-09-30,4530000,NaN

In [136]:
ss_count = ss_df.shape[0]
ss_count

100

In [137]:
ss_data = ss_df.iloc[[0],[-3]]
ss_data = ss_data.values[0]
ss_data

array(['2021-09-30'], dtype=object)

In [138]:
seos_df = pd.DataFrame({'State':['충청남도'], 'City':['서산시'], 'cnt':[ss_count], '기준일':ss_data})
seos_df

  State City  cnt         기준일
0  충청남도  서산시  100  2021-09-30

### 홍성군

In [139]:
# 홍성군 데이터 프레임 만들기
hs_df = (cn_df.시군구명 == '홍성군')
hs_df = cn_df[hs_df]
hs_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
110,4235,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 소향리 397-174,36.607824,126.647685,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
111,4236,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 소향리 397-174,36.607580,126.647700,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
112,4237,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 소향리 415-1,36.605167,126.661446,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
113,4238,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 소향리 70-4,36.605216,126.661009,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
114,4239,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 소향리 70-4,36.605274,126.660527,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,4330,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 월산리 895-5,36.599760,126.650977,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
206,4331,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 월산리 896-1,36.599764,126.651335,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
207,4332,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 월산리 896-3,36.599752,126.651883,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
208,4333,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 월산리 896-6,36.599574,126.652520,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN
209,4334,1,충청남도,홍성군,-,NaN,충청남도 홍성군 홍성읍 옥암리 112-7,36.594539,126.653136,1,...,N,NaN,NaN,NaN,NaN,홍성군,041-630-1582,2021-07-31,4600000,NaN

In [140]:
hs_count = hs_df.shape[0]
hs_count

100

In [141]:
hs_data = hs_df.iloc[[0],[-3]]
hs_data = hs_data.values[0]
hs_data

array(['2021-07-31'], dtype=object)

In [142]:
hongs_df = pd.DataFrame({'State':['충청남도'], 'City':['홍성군'], 'cnt':[hs_count], '기준일':hs_data})
hongs_df

  State City  cnt         기준일
0  충청남도  홍성군  100  2021-07-31

### 당진시

In [143]:
# 당진시 데이터 프레임 만들기
daj_df = (cn_df.시군구명 == '당진시')
daj_df = cn_df[daj_df]
daj_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
210,4335,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.885817,126.649275,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
211,4336,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-128,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
212,4337,2,충청남도,당진시,남부로,NaN,충청남도 당진시 대덕동 1288-17,36.880991,126.651985,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
213,4338,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.884730,126.653866,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
214,4339,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.885387,126.653996,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
215,4340,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.883985,126.653591,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
216,4341,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.882009,126.653758,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
217,4342,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.879702,126.656352,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
218,4343,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.878412,126.656722,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
219,4344,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.879151,126.656466,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
220,4345,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.880492,126.655446,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
221,4346,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.880903,126.654840,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4542,2021-09-23,5680000,NaN
222,4347,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.880123,126.655896,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
223,4348,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.886077,126.649872,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
224,4349,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.886325,126.650578,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
225,4350,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.886250,126.652112,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
226,4351,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.886272,126.651357,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
227,4352,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.881421,126.654179,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
228,4353,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.883250,126.653506,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
229,4354,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.882629,126.653447,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
230,4355,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.885879,126.653517,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
231,4356,2,충청남도,당진시,동부1로,NaN,충청남도 당진시 수청동 933-4,36.886002,126.652934,1,...,N,NaN,NaN,NaN,2019.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
232,4357,2,충청남도,당진시,남부로,NaN,충청남도 당진시 대덕동 1288-17,36.880991,126.651985,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4542,2021-09-23,5680000,NaN
233,4358,2,충청남도,당진시,남부로,NaN,충청남도 당진시 대덕동 1288-17,36.880991,126.651985,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
234,4359,2,충청남도,당진시,갈산길,NaN,충청남도 당진시 순성면 갈산리 753,NaN,NaN,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
235,4360,2,충청남도,당진시,갈산길,NaN,충청남도 당진시 순성면 성북리 97-2,NaN,NaN,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
236,4361,2,충청남도,당진시,버들길,NaN,충청남동 당진시 순성면 성북리 149-1,NaN,NaN,1,...,N,NaN,NaN,NaN,2020.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
237,4362,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-121,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
238,4363,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-122,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
239,4364,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-123,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
240,4365,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-124,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
241,4366,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-125,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
242,4367,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-126,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN
243,4368,2,충청남도,당진시,서해로,NaN,충청남도 당진시 읍내동 695-127,NaN,NaN,1,...,N,NaN,NaN,NaN,2021.0,충청남도 당진시,041-350-4545,2021-09-23,5680000,NaN

In [144]:
daj_count = daj_df.shape[0]
daj_count

34

In [145]:
daj_data = daj_df.iloc[[0],[-3]]
daj_data = daj_data.values[0]
daj_data

array(['2021-09-23'], dtype=object)

In [146]:
dangj_df = pd.DataFrame({'State':['충청남도'], 'City':['당진시'], 'cnt':[daj_count], '기준일':daj_data})
dangj_df

  State City  cnt         기준일
0  충청남도  당진시   34  2021-09-23

### 아산시

In [147]:
# 아산시 데이터 프레임 만들기
as_df = (cn_df.시군구명 == '아산시')
as_df = cn_df[as_df]
as_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
244,4369,2,충청남도,아산시,도송로 79,NaN,충청남도 아산시 도고면 오암리 177-1,36.718149,126.928764,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
245,4370,2,충청남도,아산시,도고산로 337,NaN,충청남도 아산시 도고면 도산리 136-2,36.731381,126.917310,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
246,4371,2,충청남도,아산시,433-10 신유리마을회관,NaN,충청남도 아산시 도고면 신유리 449,36.738372,126.914870,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
247,4372,2,충청남도,아산시,도고산로608번길,NaN,충청남도 아산시 도고면 시전리 210,36.747656,126.898915,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
248,4373,2,충청남도,아산시,고균길 21-4,NaN,충청남도 아산시 영인면 아산리 79,36.852399,126.956949,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
249,4374,2,충청남도,아산시,토정샘로 222,NaN,충청남도 아산시 영인면 성내리 580-1,36.874297,126.987567,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
250,4375,2,충청남도,아산시,토정샘로 222,NaN,충청남도 아산시 영인면 성내리 603-1,36.874100,126.986800,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
251,4376,2,충청남도,아산시,토정샘로 222,NaN,충청남도 아산시 영인면 성내리 570-2,36.873505,126.985575,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
252,4377,2,충청남도,아산시,토정샘로 222,NaN,충청남도 아산시 영인면 성내리 639-2,36.872543,126.983844,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
253,4378,2,충청남도,아산시,토정샘로 222,NaN,충청남도 아산시 영인면 성내리 654-10,36.872773,126.982438,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
254,4379,2,충청남도,아산시,아산만로 1548번길 11,NaN,충청남도 아산시 인주면 문방리 378-2,36.864228,126.870324,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
255,4380,2,충청남도,아산시,아산만로 1572,NaN,충청남도 아산시 인주면 문방리 97-16,36.865884,126.872414,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
256,4381,2,충청남도,아산시,아산만로 353,NaN,충청남도 아산시 선장면 군덕리 505,36.812577,126.863506,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
257,4382,2,충청남도,아산시,대흥길 48-1,NaN,충청남도 아산시 선장면 대흥리 251-1,36.774749,126.871231,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
258,4383,2,충청남도,아산시,운용길 20,NaN,충청남도 아산시 둔포면 운용리 339-4,36.934719,127.057135,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
259,4384,2,충청남도,아산시,운용길 27,NaN,충청남도 아산시 둔포면 운용리 339-9,36.935472,127.056531,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
260,4385,2,충청남도,아산시,운용길 51-3,NaN,충청남도 아산시 둔포면 운용리 338-8,36.933858,127.058134,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
261,4386,2,충청남도,아산시,둔포중앙로133번길 11-1,NaN,충청남도 아산시 둔포면 둔포리 470-15,36.928953,127.039491,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
262,4387,2,충청남도,아산시,둔포중앙로133번길 23-14,NaN,충청남도 아산시 둔포면 둔포리 253-7,36.930010,127.041101,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
263,4388,2,충청남도,아산시,아산호로 1046,NaN,충청남도 아산시 둔포면 신법리 183-5,36.923812,127.015625,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
264,4389,2,충청남도,아산시,충무로1313번길 25-18,NaN,충청남도 아산시 둔포면 봉재리 272-4,36.888695,127.031390,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
265,4390,2,충청남도,아산시,고균길 1,NaN,충청남도 아산시 영인면 아산리 135-2,36.853830,126.957506,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
266,4391,2,충청남도,아산시,고균길 1,NaN,충청남도 아산시 영인면 아산리 135-8,36.853469,126.957520,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
267,4392,2,충청남도,아산시,고균길 1,NaN,충청남도 아산시 영인면 아산리 83-12,36.853132,126.957539,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
268,4393,2,충청남도,아산시,고균길 1,NaN,충청남도 아산시 영인면 아산리 83-13,36.852591,126.957302,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
269,4394,2,충청남도,아산시,고균길 21-4,NaN,충청남도 아산시 영인면 아산리 83-26,36.852103,126.957350,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
270,4395,2,충청남도,아산시,송악로 181,NaN,충청남도 아산시 송악면 강장리 573,36.717642,126.958131,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
271,4396,2,충청남도,아산시,음봉로 471,NaN,충청남도 아산시 음봉면 동암리 251-4,36.842585,127.060305,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
272,4397,2,충청남도,아산시,음봉로 471,NaN,충청남도 아산시 음봉면 동암리 228-3,36.842191,127.063033,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
273,4398,2,충청남도,아산시,음봉로 471,NaN,충청남도 아산시 음봉면 동암리 262-4,36.841267,127.065836,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
274,4399,2,충청남도,아산시,음봉로 471,NaN,충청남도 아산시 음봉면 동암리 263-1,36.840805,127.067146,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
275,4400,2,충청남도,아산시,음봉로 567,NaN,충청남도 아산시 음봉면 월랑리 163-6,36.843495,127.075115,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
276,4401,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 177-1,36.843709,127.076669,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
277,4402,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 197-5,36.844106,127.078155,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
278,4403,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 253,36.849501,127.075749,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
279,4404,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 246-3,36.848435,127.075372,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
280,4405,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 188-9,36.842607,127.078131,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
281,4406,2,충청남도,아산시,월암로 72,NaN,충청남도 아산시 음봉면 월랑리 128-5,36.841291,127.078672,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
282,4407,2,충청남도,아산시,음봉로681번길 76,NaN,충청남도 아산시 음봉면 월랑리 119-1,36.838762,127.080689,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
283,4408,2,충청남도,아산시,음봉로681번길 31,NaN,충청남도 아산시 음봉면 덕지리 28-7,36.837425,127.083479,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
284,4409,2,충청남도,아산시,음봉로681번길 40-11,NaN,충청남도 아산시 음봉면 덕지리 14-3,36.838645,127.083277,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
285,4410,2,충청남도,아산시,음봉로681번길 24,NaN,충청남도 아산시 음봉면 덕지리 24-2,36.839686,127.083339,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
286,4411,2,충청남도,아산시,음봉로681번길 28,NaN,충청남도 아산시 음봉면 덕지리 33-3,36.836494,127.084236,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
287,4412,2,충청남도,아산시,월산로 266,NaN,충청남도 아산시 음봉면 산동리 815-1,36.849892,127.097536,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
288,4413,2,충청남도,아산시,산동안길 14,NaN,충청남도 아산시 음봉면 산동리 420-2,36.831373,127.096612,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
289,4414,2,충청남도,아산시,71-1 라온빌,NaN,충청남도 아산시 둔포면 운용리 337-164,36.931688,127.059258,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN
290,4415,2,충청남도,아산시,운용길 27,NaN,충청남도 아산시 둔포면 운용리 338-1,36.934475,127.057530,1,...,N,NaN,NaN,NaN,2018.0,아산시,041-540-2943,2020-06-30,4520000,NaN

In [148]:
as_count = as_df.shape[0]
as_count

47

In [149]:
as_data = as_df.iloc[[0],[-3]]
as_data = as_data.values[0]
as_data

array(['2020-06-30'], dtype=object)

In [150]:
asan_df = pd.DataFrame({'State':['충청남도'], 'City':['아산시'], 'cnt':[as_count], '기준일':as_data})
asan_df

  State City  cnt         기준일
0  충청남도  아산시   47  2020-06-30

### 공주시

In [151]:
# 공주시 데이터 프레임 만들기
gj_df = (cn_df.시군구명 == '공주시')
gj_df = cn_df[gj_df]
gj_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
291,4416,2,충청남도,공주시,하선길,하선길27,금학동231-1,36.441244,127.117840,1,...,N,NaN,무,NaN,2019.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
292,4417,2,충청남도,공주시,중앙공원길,중앙공원2길7,중동264,35.982752,126.725389,1,...,N,NaN,무,NaN,2019.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
293,4418,2,충청남도,공주시,번영로,번영3로 5,신관동 607-13,36.467944,127.132661,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
294,4419,2,충청남도,공주시,무령로,무령로600-25,월송동 619,36.466996,127.155769,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
295,4420,2,충청남도,공주시,석장리동,석장리동대추골길 15,석장리동 415,36.456372,127.190102,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
296,4421,2,충청남도,공주시,양지마을길,양지마을2길 15,금학동 275-3,36.441542,127.121047,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
297,4422,2,충청남도,공주시,고상아리길,고상아리1길 12-1,중학동 70-3,36.450086,127.124895,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
298,4423,2,충청남도,공주시,마티고개로,반포면 마티고개로 268,반포면 마암리 산 46-2,36.408140,127.221414,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN
299,4424,2,충청남도,공주시,솔바람길,반포면 솔바람길 17,반포면 봉곡리 172,36.407024,127.239349,1,...,N,NaN,무,NaN,2020.0,공주시청,041-840-8118,2021-10-22,4500000,NaN

In [152]:
gj_count = gj_df.shape[0]
gj_count

9

In [153]:
gj_data = gj_df.iloc[[0],[-3]]
gj_data = gj_data.values[0]
gj_data

array(['2021-10-22'], dtype=object)

In [154]:
gongj_df = pd.DataFrame({'State':['충청남도'], 'City':['공주시'], 'cnt':[gj_count], '기준일':gj_data})
gongj_df

  State City  cnt         기준일
0  충청남도  공주시    9  2021-10-22

### 보령시

In [155]:
# 보령시 데이터 프레임 만들기
br_df = (cn_df.시군구명 == '보령시')
br_df = cn_df[br_df]
br_df

,시스템키,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,...,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자,제공기관코드,제공기관명
300,4425,2,충청남도,보령시,대해로,NaN,충청남도 보령시 궁촌동 25-3,36.343121,126.594156,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
301,4426,2,충청남도,보령시,대해로,NaN,충청남도 보령시 궁촌동 25-10,36.343436,126.594741,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
302,4427,2,충청남도,보령시,구장터로,충청남도 보령시 구장터로 48-4,충청남도 보령시 대천동 222-3,36.347078,126.595223,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
303,4428,2,충청남도,보령시,구장터로,NaN,충청남도 보령시 대천동 261-9,36.347734,126.595302,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
304,4429,2,충청남도,보령시,구장터로,충청남도 보령시 구장터로 33,충청남도 보령시 대천동 618-89,36.347531,126.595612,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
305,4430,2,충청남도,보령시,대해로,NaN,충청남도 보령시 궁촌동 362,36.343303,126.592308,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
306,4431,2,충청남도,보령시,대천항로,NaN,충청남도 보령시 신흑동 911-135,36.323028,126.509831,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
307,4432,2,충청남도,보령시,대천항로,NaN,충청남도 보령시 신흑동 산208-4,36.323072,126.509343,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
308,4433,2,충청남도,보령시,대천항로,NaN,충청남도 보령시 신흑동 911-71,36.324064,126.509711,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
309,4434,2,충청남도,보령시,시영길,충청남도 보령시 시영길 18,충청남도 보령시 신흑동 911-51,36.322985,126.510551,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
310,4435,2,충청남도,보령시,구시9길,NaN,충청남도 보령시 대천동 318-59,36.348175,126.592766,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
311,4436,2,충청남도,보령시,구시11길,NaN,충청남도 보령시 대천동 629-8,36.346766,126.592764,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
312,4437,2,충청남도,보령시,해망산길,NaN,충청남도 보령시 요암동 611-2,36.323708,126.541799,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
313,4438,2,충청남도,보령시,대해로,NaN,충청남도 보령시 내항동 336-3,36.341505,126.587512,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
314,4439,2,충청남도,보령시,중앙로,충청남도 보령시 중앙로 278,충청남도 보령시 대천동 524-5,36.361369,126.583812,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
315,4440,2,충청남도,보령시,동현로,충청남도 보령시 동현로 3,충청남도 보령시 동대동 681-4,36.352332,126.608572,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
316,4441,2,충청남도,보령시,대흥로,NaN,충청남도 보령시 대천동 337-26,36.349755,126.591716,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
317,4442,2,충청남도,보령시,군마루2길,NaN,충청남도 보령시 신흑동 81-5,36.323697,126.539890,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
318,4443,2,충청남도,보령시,대해로,NaN,충청남도 보령시 궁촌동 24-1,36.343722,126.594224,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
319,4444,2,충청남도,보령시,명암2길,충청남도 보령시 명암2길 21,충청남도 보령시 명천동 172-16,36.342151,126.616835,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
320,4445,2,충청남도,보령시,대천로,충청남도 보령시 대천로 144,충청남도 보령시 죽정동 421-1,36.357975,126.607795,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
321,4446,2,충청남도,보령시,대터골길,NaN,충청남도 보령시 주교면 주교리 675-2,36.390477,126.558471,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
322,4447,2,충청남도,보령시,관창공단길,NaN,충청남도 보령시 주교면 관창리 470-2,36.368686,126.579284,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
323,4448,2,충청남도,보령시,배재길,NaN,충청남도 보령시 주포면 관산리 306-1,36.406202,126.583214,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
324,4449,2,충청남도,보령시,넙티로,NaN,충청남도 보령시 청소면 진죽리 53-2,36.442316,126.599952,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
325,4450,2,충청남도,보령시,청소큰길,NaN,충청남도 보령시 청소면 진죽리 284,36.451381,126.593042,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
326,4451,2,충청남도,보령시,놀문이길,NaN,충청남도 보령시 천북면 사호리 708,36.492186,126.493519,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
327,4452,2,충청남도,보령시,서해안고속도로,NaN,충청남도 보령시 남포면 제석리 6-2,36.324715,126.584111,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
328,4453,2,충청남도,보령시,창동3길,NaN,충청남도 보령시 남포면 창동리 651-22,36.317798,126.604346,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
329,4454,2,충청남도,보령시,야동2길,NaN,충청남도 보령시 남포면 달산리 262,36.296966,126.589542,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
330,4455,2,충청남도,보령시,은현내동길,NaN,충청남도 보령시 미산면 옥현리 178,36.223222,126.707666,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
331,4456,2,충청남도,보령시,만수로,NaN,충청남도 보령시 성주면 개화리 642-142,36.291318,126.646558,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
332,4457,2,충청남도,보령시,성주산로,NaN,충청남도 보령시 성주면 성주리 산39,36.332943,126.664020,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
333,4458,2,충청남도,보령시,대관초등길,NaN,충청남도 보령시 대천동 503-16,36.357422,126.585243,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
334,4459,2,충청남도,보령시,원뚝길,NaN,충청남도 보령시 대천동 1233,36.348740,126.587504,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
335,4460,2,충청남도,보령시,쇳개길,충청남도 보령시 쇳개길 28,충청남도 보령시 대천동 297-43,36.347281,126.588814,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
336,4461,2,충청남도,보령시,됫박산2길,충청남도 보령시 됫박산2길 16,충청남도 보령시 신흑동 1440-45,36.309200,126.519736,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
337,4462,2,충청남도,보령시,새마을2길,NaN,충청남도 보령시 신흑동 1775-236,36.307937,126.518851,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
338,4463,2,충청남도,보령시,소리길,NaN,충청남도 보령시 대천동 545,36.360965,126.579961,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
339,4464,2,충청남도,보령시,두러뫼길,NaN,충청남도 보령시 동대동 658-4,36.354861,126.606714,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
340,4465,2,충청남도,보령시,수로길,NaN,충청남도 보령시 동대동 561-7,36.348267,126.610273,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
341,4466,2,충청남도,보령시,천변남길,NaN,충청남도 보령시 동대동 727-16,36.352458,126.603240,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
342,4467,2,충청남도,보령시,신설1길,충청남도 보령시 신설1길 15,충청남도 보령시 동대동 1956,36.349361,126.604425,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN
343,4468,2,충청남도,보령시,됫박산1길,충청남도 보령시 됫박산1길 31,충청남도 보령시 신흑동 1440-49,36.310079,126.520294,1,...,N,NaN,NaN,NaN,NaN,충청남도 보령시청,041-930-3991,2022-08-11,4510000,NaN

In [156]:
br_count = br_df.shape[0]
br_count

44

In [157]:
br_data = br_df.iloc[[0],[-3]]
br_data = br_data.values[0]
br_data

array(['2022-08-11'], dtype=object)

In [158]:
bory_df = pd.DataFrame({'State':['충청남도'], 'City':['보령시'], 'cnt':[br_count], '기준일':br_data})
bory_df

  State City  cnt         기준일
0  충청남도  보령시   44  2022-08-11

In [159]:
chungnam_all_df_merged = pd.concat([byeo_df, seos_df, hongs_df, dangj_df, asan_df, gongj_df, bory_df])
chungnam_all_df_merged = chungnam_all_df_merged.reset_index(drop = True)
chungnam_all_df_merged

  State City  cnt         기준일
0  충청남도  부여군   10  2022-07-19
1  충청남도  서산시  100  2021-09-30
2  충청남도  홍성군  100  2021-07-31
3  충청남도  당진시   34  2021-09-23
4  충청남도  아산시   47  2020-06-30
5  충청남도  공주시    9  2021-10-22
6  충청남도  보령시   44  2022-08-11

## 충청북도

In [160]:
cb_df = pd.read_csv('./mydata/chungbuck/cb.csv', encoding='cp949')
cb_df

,스마트가로등유형,시도명,시군구명,도로명,소재지도로명주소,소재지지번주소,위도,경도,스마트가로등형태,점등상태여부,...,비콘유무,조명제어여부,위급상황신고가능여부,앱서비스명,앱서비스제공내용,기타서비스,설치년도,관리기관명,관리기관전화번호,데이터기준일자
0,1,11,진천군,바들말길,NaN,충청북도 진천군 광혜원면 광혜원리 120-1,36.993143,127.447033,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
1,1,11,진천군,바들말4길,NaN,충청북도 진천군 광혜원면 광혜원리 178-11,36.993071,127.447078,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
2,1,11,진천군,바들말4길,NaN,충청북도 진천군 광혜원면 광혜원리 178-11,36.993044,127.447045,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
3,1,11,진천군,바들말4길,NaN,충청북도 진천군 광혜원면 광혜원리 182-2,36.991490,127.448101,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
4,1,11,진천군,바들말4길,NaN,충청북도 진천군 광혜원면 광혜원리 183-1,36.991499,127.447977,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,1,11,진천군,문화6길,NaN,충청북도 진천군 진천읍 장관리 135-22,36.864799,127.431728,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
117,1,11,진천군,진광로,NaN,충청북도 진천군 진천읍 장관리 6-2,36.871872,127.440851,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
118,1,11,진천군,진광로,NaN,충청북도 진천군 진천읍 장관리 6-9,36.871947,127.441523,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
119,1,11,진천군,장관교,NaN,충청북도 진천군 진천읍 행정리 880-3,36.866597,127.423202,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01
120,1,11,진천군,초평로,NaN,충청북도 진천군 초평면 중석리 384-1,36.846264,127.498368,1,N,...,N,Y,Y,양방향관제시스템,천재지변이나 위급한 상황시 원격으로 분전함 제어및 고장시 문자 통보,전력값 측정,2014,충청북도 진천군,043-539-3362,2018-08-01

In [161]:
cb_count = cb_df.shape[0]
cb_count

121

In [162]:
cb_data = cb_df.iloc[[0],[-1]]
cb_data = cb_data.values[0]
cb_data

array(['2018-08-01'], dtype=object)

In [163]:
chungbuck_all_df_merged = pd.DataFrame({'State':['충청북도'], 'City':['진천군'], 'cnt':[cb_count], '기준일':cb_data})
chungbuck_all_df_merged

  State City  cnt         기준일
0  충청북도  진천군  121  2018-08-01

## 전체 데이터 합치기

In [164]:
df_strlamp = pd.concat([busan_all_df_merged, seoul_all_df_merged, sejong_all_df_merged, incheon_all_df_merged, jeonnam_all_df_merged, chungnam_all_df_merged, chungbuck_all_df_merged])
df_strlamp = df_strlamp.reset_index(drop = True)
df_strlamp

      State  City      cnt         기준일
0     부산광역시    동구   2900.0        None
1     부산광역시   동래구   4532.0        None
2     부산광역시    북구   4521.0        None
3     부산광역시   강서구  19623.0        None
4     부산광역시    진구   8258.0  2022-10-18
5     부산광역시    중구   1777.0        None
6     부산광역시   기장군  11333.0        None
7     부산광역시    남구   4453.0        None
8     부산광역시   사하구   6042.0  2022-05-09
9     부산광역시    서구   2848.0  2023-01-13
10    부산광역시   수영구   4009.0        None
11    부산광역시   연재구   3922.0        None
12    서울특별시   광진구   2722.0        None
13    서울특별시  서대문구   3230.0        None
14    서울특별시   용산구   3605.0        None
15    서울특별시   도봉구    627.0  2018-01-01
16    서울특별시  동대문구   5205.0        None
17    서울특별시   관악구   3026.0        None
18    서울특별시   광진구   1993.0  2022-02-12
19    서울특별시   중랑구   6419.0  2023-02-14
20    서울특별시   양천구   4836.0  2022-09-30
21    서울특별시  영등포구   9615.0  2022-11-03
22  세종특별자치시        15460.0  2022-08-23
23    인천광역시    중구   3230.0  2022-10-12
24    인천광역시  미추홀구   4407.0  2022-08-04
25    인천광역시   남동구  17820.0  2022-08-24
26    인천광역시   옹진군   2055.0  2022-04-21
27    인천광역시    서구  22540.0        None
28     전라남도   곡성군   3230.0  2023-02-01
29     전라남도   순천시  10725.0  2021-09-01
30     전라남도   해남군   1993.0  2022-05-18
31     충청남도   부여군     10.0  2022-07-19
32     충청남도   서산시    100.0  2021-09-30
33     충청남도   홍성군    100.0  2021-07-31
34     충청남도   당진시     34.0  2021-09-23
35     충청남도   아산시     47.0  2020-06-30
36     충청남도   공주시      9.0  2021-10-22
37     충청남도   보령시     44.0  2022-08-11
38     충청북도   진천군    121.0  2018-08-01

In [165]:
df_strlamp.rename(columns={'State':'state', 'City':'city', 'cnt':'install_cnt', '기준일':'date'}, inplace=True)

In [166]:
df_strlamp

      state  city  install_cnt        date
0     부산광역시    동구       2900.0        None
1     부산광역시   동래구       4532.0        None
2     부산광역시    북구       4521.0        None
3     부산광역시   강서구      19623.0        None
4     부산광역시    진구       8258.0  2022-10-18
5     부산광역시    중구       1777.0        None
6     부산광역시   기장군      11333.0        None
7     부산광역시    남구       4453.0        None
8     부산광역시   사하구       6042.0  2022-05-09
9     부산광역시    서구       2848.0  2023-01-13
10    부산광역시   수영구       4009.0        None
11    부산광역시   연재구       3922.0        None
12    서울특별시   광진구       2722.0        None
13    서울특별시  서대문구       3230.0        None
14    서울특별시   용산구       3605.0        None
15    서울특별시   도봉구        627.0  2018-01-01
16    서울특별시  동대문구       5205.0        None
17    서울특별시   관악구       3026.0        None
18    서울특별시   광진구       1993.0  2022-02-12
19    서울특별시   중랑구       6419.0  2023-02-14
20    서울특별시   양천구       4836.0  2022-09-30
21    서울특별시  영등포구       9615.0  2022-11-03
22  세종특별자치시            15460.0  2022-08-23
23    인천광역시    중구       3230.0  2022-10-12
24    인천광역시  미추홀구       4407.0  2022-08-04
25    인천광역시   남동구      17820.0  2022-08-24
26    인천광역시   옹진군       2055.0  2022-04-21
27    인천광역시    서구      22540.0        None
28     전라남도   곡성군       3230.0  2023-02-01
29     전라남도   순천시      10725.0  2021-09-01
30     전라남도   해남군       1993.0  2022-05-18
31     충청남도   부여군         10.0  2022-07-19
32     충청남도   서산시        100.0  2021-09-30
33     충청남도   홍성군        100.0  2021-07-31
34     충청남도   당진시         34.0  2021-09-23
35     충청남도   아산시         47.0  2020-06-30
36     충청남도   공주시          9.0  2021-10-22
37     충청남도   보령시         44.0  2022-08-11
38     충청북도   진천군        121.0  2018-08-01

In [175]:
df_j = pd.read_csv('./df_jyong.csv')

In [176]:
df_j

    Unnamed: 0  state  city  install_cnt        date
0            0    경기도   안산시        21173  2022-06-21
1            1    경기도   광주시         7529         NaN
2            2    경기도   김포시        19499  2022-02-24
3            3    경기도   고양시           42         NaN
4            4    경기도   화성시        43553  2022-11-30
5            5    경기도   수원시        24704  2022-10-07
6            6    경기도   의왕시        10462         NaN
7            7    경기도   양평군         1830  2022-12-30
8            8    강원도   춘천시        12850  2021-10-18
9            9   경상북도   포항시        11765         NaN
10          10   경상북도   경주시         5905         NaN
11          11   경상북도   김천시         6006         NaN
12          12   경상북도   안동시        13433         NaN
13          13   경상북도   구미시        11181         NaN
14          14   경상북도   영주시         9211         NaN
15          15   경상북도   영천시         2889         NaN
16          16   경상북도   상주시         2138         NaN
17          17   경상북도   문경시        10596         NaN
18          18   경상북도   경산시         6008         NaN
19          19   경상북도   군위군         3446         NaN
20          20   경상북도   의성군          767         NaN
21          21   경상북도   청송군         3618         NaN
22          22   경상북도   영양군         2455         NaN
23          23   경상북도   영덕군         5736         NaN
24          24   경상북도   청도군         1238         NaN
25          25   경상북도   고령군          880         NaN
26          26   경상북도   성주군         5843         NaN
27          27   경상북도   칠곡군         9952         NaN
28          28   경상북도   예천군          770         NaN
29          29   경상북도   봉화군         4830         NaN
30          30   경상북도   울진군         8254         NaN
31          31   경상북도   울릉군         1189         NaN
32          32  광주광역시    남구         3052  2021-11-03
33          33  광주광역시    북구         6563  2022-11-10
34          34  대전광역시    서구         9244         NaN
35          35  대전광역시   대덕구         5824         NaN
36          36  대전광역시    동구         5790         NaN
37          37  대전광역시   유성구        17266         NaN
38          38  대전광역시    중구         4958         NaN
39          39   전라북도   군산시        16668         NaN
40          40    제주도   제주시        43465         NaN
41          41    제주도  서귀포시        29567         NaN

In [177]:
df_j.drop(['Unnamed: 0'],axis=1, inplace=True)
df_j

    state  city  install_cnt        date
0     경기도   안산시        21173  2022-06-21
1     경기도   광주시         7529         NaN
2     경기도   김포시        19499  2022-02-24
3     경기도   고양시           42         NaN
4     경기도   화성시        43553  2022-11-30
5     경기도   수원시        24704  2022-10-07
6     경기도   의왕시        10462         NaN
7     경기도   양평군         1830  2022-12-30
8     강원도   춘천시        12850  2021-10-18
9    경상북도   포항시        11765         NaN
10   경상북도   경주시         5905         NaN
11   경상북도   김천시         6006         NaN
12   경상북도   안동시        13433         NaN
13   경상북도   구미시        11181         NaN
14   경상북도   영주시         9211         NaN
15   경상북도   영천시         2889         NaN
16   경상북도   상주시         2138         NaN
17   경상북도   문경시        10596         NaN
18   경상북도   경산시         6008         NaN
19   경상북도   군위군         3446         NaN
20   경상북도   의성군          767         NaN
21   경상북도   청송군         3618         NaN
22   경상북도   영양군         2455         NaN
23   경상북도   영덕군         5736         NaN
24   경상북도   청도군         1238         NaN
25   경상북도   고령군          880         NaN
26   경상북도   성주군         5843         NaN
27   경상북도   칠곡군         9952         NaN
28   경상북도   예천군          770         NaN
29   경상북도   봉화군         4830         NaN
30   경상북도   울진군         8254         NaN
31   경상북도   울릉군         1189         NaN
32  광주광역시    남구         3052  2021-11-03
33  광주광역시    북구         6563  2022-11-10
34  대전광역시    서구         9244         NaN
35  대전광역시   대덕구         5824         NaN
36  대전광역시    동구         5790         NaN
37  대전광역시   유성구        17266         NaN
38  대전광역시    중구         4958         NaN
39   전라북도   군산시        16668         NaN
40    제주도   제주시        43465         NaN
41    제주도  서귀포시        29567         NaN

In [178]:
all_df_merged = pd.concat([df_strlamp, df_j])
all_df_merged = all_df_merged.reset_index(drop = True)
all_df_merged['install_cnt'] = all_df_merged['install_cnt'].astype(int)
all_df_merged

    state  city  install_cnt        date
0   부산광역시    동구         2900        None
1   부산광역시   동래구         4532        None
2   부산광역시    북구         4521        None
3   부산광역시   강서구        19623        None
4   부산광역시    진구         8258  2022-10-18
..    ...   ...          ...         ...
76  대전광역시   유성구        17266         NaN
77  대전광역시    중구         4958         NaN
78   전라북도   군산시        16668         NaN
79    제주도   제주시        43465         NaN
80    제주도  서귀포시        29567         NaN

[81 rows x 4 columns]